package v9t9.base.winmm;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class WAVEOUTCAPSA extends Structure<WAVEOUTCAPSA, WAVEOUTCAPSA.ByValue, WAVEOUTCAPSA.ByReference> {
	public short wMid;
	public short wPid;
	/// Conversion Error : UINT
	/// C type : CHAR[32]
	public com.sun.jna.Pointer szPname;
	public int dwFormats;
	public short wChannels;
	public short wReserved1;
	public int dwSupport;
	public WAVEOUTCAPSA() {
		super();
	}
	/// @param szPname C type : CHAR[32]
	public WAVEOUTCAPSA(short wMid, short wPid, com.sun.jna.Pointer szPname, int dwFormats, short wChannels, short wReserved1, int dwSupport) {
		super();
		this.wMid = wMid;
		this.wPid = wPid;
		this.szPname = szPname;
		this.dwFormats = dwFormats;
		this.wChannels = wChannels;
		this.wReserved1 = wReserved1;
		this.dwSupport = dwSupport;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected WAVEOUTCAPSA newInstance() { return new WAVEOUTCAPSA(); }
	public static WAVEOUTCAPSA[] newArray(int arrayLength) {
		return Structure.newArray(WAVEOUTCAPSA.class, arrayLength);
	}
	public static class ByReference extends WAVEOUTCAPSA implements Structure.ByReference {}
	public static class ByValue extends WAVEOUTCAPSA implements Structure.ByValue {}
}
