/**
 * 
 */
package v9t9.audio.sound;

import java.util.Arrays;

import ejs.base.settings.ISettingSection;
import ejs.base.sound.IFlushableSoundVoice;

/**
 * Reproduce the sound generated by the cassette recording.
 * 
 * From &lt;http://nouspikel.com/ti99/tms9901.htm#Ti99&gt;
 * 
 * <pre>
 * Pin INT13* / P9 is used to output sound to the cassette, this will be digital sound of course, modulated via an electronic circuit in the console.
 * </pre>
 * And from &lt;http://nouspikel.group.shef.ac.uk//ti99/cassette.htm#Cassette%20tape%20format&gt;:
 * 
 * <pre>
 * Texas Instruments adopted a frequency modulation encoding system to store data on tape. 
 * This is only a convention, and you may come up with another, if you feel like it. Similarly, TI defined the format the data 
 * should have whithin a tape file. Again, this is only a convention.
 * </pre>
 * 
 * (From the above, the modulation is not a convention!)
 * @author ejs
 *
 */
public class CassetteSoundVoice extends ClockedSoundVoice implements IFlushableSoundVoice {

	private double CARRIER_FREQ = 690;
	private double MODULATOR_FREQ = 1380;
	private boolean wasSet;
	private boolean state;
	private boolean origState;
	private int phaseCtr = Integer.MAX_VALUE;
	private int onTime = 0;
	private int[] deltas = new int[0];
	private int deltaIdx = 0;
	private int baseCycles;
	
	public CassetteSoundVoice(String name) {
		super((name != null ? name + " " : "") + "Cassette");
	}
	
	@Override
	public void setupVoice() {
		setVolume((byte) (state ? MAX_VOLUME : 0));
		wasSet = true;
	}

	/* (non-Javadoc)
	 * @see org.ejs.emul.core.sound.ISoundVoice#setSoundClock(int)
	 */
	public void setSoundClock(int soundClock) {
		this.soundClock = soundClock;
	}
	
	/* (non-Javadoc)
	 * @see org.ejs.emul.core.sound.ISoundVoice#reset()
	 */
	public void reset() {
		wasSet = false;
		origState = false;
		deltaIdx = 0;
		baseCycles = 0;
		phaseCtr = 0;
		onTime = 0;
	}
	
	/* (non-Javadoc)
	 * @see v9t9.engine.sound.SoundVoice#isActive()
	 */
	@Override
	public boolean isActive() {
		return super.isActive();
	}
	public synchronized void setState(int curr) {
		boolean newState = curr >= 0;
		if (state != newState) {
			int offs = absp1(curr) - baseCycles;
			if (offs < 0)
				offs = curr;
			baseCycles = curr;
			state = newState;
			appendPos(state ? offs : -offs-1);
		}
	}

	/**
	 * @param pos
	 * @throws AssertionError
	 */
	protected void appendPos(int pos) throws AssertionError {
		if (deltaIdx > 0 && deltas[deltaIdx - 1] == pos)
			return;
		
		if (deltaIdx >= deltas.length) {
			int newlen = deltas.length * 2;
			if (newlen < 16)
				newlen = 16;
			deltas = Arrays.copyOf(deltas, newlen);
		}
		
		deltas[deltaIdx++] = pos;
	}

	public boolean generate(float[] soundGeneratorWorkBuffer, int from,
			int to) {
		
		//appendPos(state ? totalCount : -totalCount-1);
		return wasSet;
	}

	/* (non-Javadoc)
	 * @see v9t9.base.sound.ITimeAdjustSoundVoice#flushAudio(float[], int, int)
	 */
	@Override
	public synchronized boolean flushAudio(float[] soundGeneratorWorkBuffer, int from,
			int to, int total_unused) {
		boolean generated = false;
		if (from < to && (true)) {
			
			generated = true;
			int ratio = 128 + balance;
			float sampleL = ((256 - ratio) * 1f) / 256.f;
			float sampleR = (ratio * 1f) / 256.f;
			
			
			int totalSamps = to - from;
			
			int total = 0;
			for (int i = 0; i < deltaIdx; i++)
				total += absp1(deltas[i]);

			if (total == 0)
				total = 1;

			//StringBuilder sb = new StringBuilder();
			
			int idx = 0;
			int consumed = deltaIdx > 0 ? absp1(deltas[idx]) : 0;
			int next = from + (int) ((long) consumed * totalSamps / total);
			idx++;
			//sb.append(next - from).append(',');
			
			boolean on = origState;
			
			
//			phaseCtr = 0;
			//onTime = 0;
			
			while (from < to) {

				final int LIMIT = (int) (MODULATOR_FREQ / 8); // soundClock / 500;
				// only emit sound as long as different values are being written
				if (onTime < LIMIT) 
				{
					float v;
					
					double rad = phaseCtr * 2. * Math.PI / soundClock ;  
				//	double onTimeMod = Math.sin(onTime * Math.PI  / LIMIT);
					double onTimeRad = onTime *  Math.PI / soundClock ;
					v = (float) ( Math.sin(rad * CARRIER_FREQ ) * (0.5 + Math.sin(onTimeRad * MODULATOR_FREQ) ) );
//					if (on) {
//						if (onTime < LIMIT / 2)
//							onTime++;
//					} else {
////						v = (float) (Math.sin(rad * CARRIER_FREQ));
//						if (onTime < LIMIT)
//							onTime++;
//					}
					if (on)
						onTime++;
					phaseCtr++;
//					if (phaseCtr >= soundClock)
//						phaseCtr -= soundClock;
//					if (onTime >= 32)
//						onTime -= 32;
					soundGeneratorWorkBuffer[from++] += sampleL * v;
					soundGeneratorWorkBuffer[from++] += sampleR * v;
				} else {
					from += 2;
				}
				if (from >= next) {
					if (idx < deltaIdx) {
						boolean nextOn = (deltas[idx] > 0);
						consumed += absp1(deltas[idx++]);
						next = (int) ((long) consumed * totalSamps / total);
						//phaseCtr = 0; //nextOn != on ? 0 : phaseCtr;
						//onTime = nextOn != on ? onTime : 0;
//						if (nextOn)
						onTime = nextOn == on ? onTime : 0;
						//if (nextOn != on)
						//	phaseCtr = 0;
						on = nextOn;
					} else {
						on = state;
						next = to;
					}
					//sb.append(next - from).append(',');
				}
			}
			//System.out.println(sb.toString());
			//sb.setLength(0);
		}
		
		deltaIdx = 0;
		origState = state;
		baseCycles = total_unused;
		
		return generated;
	}
	
	/**
	 * @param i
	 * @return
	 */
	private int absp1(int i) {
		return i < 0 ? -(i+1) : i;
	}

	@Override
	public void loadState(ISettingSection settings) {
		if (settings == null) return;
		super.loadState(settings);
		setVolume((byte) (settings.getBoolean("State") ? MAX_VOLUME : 0));
	}
	
	@Override
	public void saveState(ISettingSection settings) {
		super.saveState(settings);
		settings.put("State", Boolean.toString(getVolume() != 0));
	}
	
}