/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_v9t9_window (void);
GtkWidget* create_quit_dialog (void);
GtkWidget* create_command_log_font_selector (void);
GtkWidget* create_disks_dialog (void);
GtkWidget* create_modules_dialog (void);
GtkWidget* create_debugger_window (void);
GtkWidget* create_memory_dialog (void);
GtkWidget* create_options_dialog (void);
GtkWidget* create_logging_dialog (void);
GtkWidget* create_fatal_dialog (void);
GtkWidget* create_completion_popup (void);
GtkWidget* create_memory_map_dialog (void);
GtkWidget* create_command_dialog (void);
