#!/bin/bash

if [ ! -d trunk ]
then
  echo "Directory \'trunk\' must exist and contain files from TCF source code repository"
  exit 1
fi

if [ -z "$VBOXUSER" ]
then
  echo "VBOXUSER is not defined"
  exit 1
fi

if [ -z "$DISPLAY" ]
then
  echo "DISPLAY is not defined"
  exit 1
fi

VBOXHOST=192.168.155.1

rm -rf java-bin || exit 1
mkdir java-bin || exit 1
SRCPATH=`pwd`/trunk/plugins/org.eclipse.tm.tcf
DSTPATH=`pwd`/java-bin
javac -g -nowarn \
  -sourcepath $SRCPATH.core/src:$SRCPATH.debug/src \
  -d $DSTPATH \
  "$SRCPATH.debug/src/org/eclipse/tm/internal/tcf/debug/tests/Main.java" \
  || exit 1

pushd "$SRCPATH.core/src/org/eclipse/tm/internal/tcf/services/remote" >/dev/null || exit 1
for FILE in `ls *.java`
do
  javac -g -nowarn \
    -classpath $DSTPATH \
    -sourcepath "$SRCPATH.core/src" \
    -d $DSTPATH \
    "$SRCPATH.core/src/org/eclipse/tm/internal/tcf/services/remote/$FILE" \
    || exit 1
done
popd >/dev/null

if ps ax | grep -q VirtualBox
then
  true
else
  VirtualBox &
fi

rm -rf logs || exit 1
mkdir logs || exit 1

CFLAGS1="\
 -DSERVICE_RunControl=0 \
 -DSERVICE_Breakpoints=0 \
 -DSERVICE_Memory=0 \
 -DSERVICE_Registers=0 \
 -DSERVICE_MemoryMap=0 \
 -DSERVICE_StackTrace=0 \
 -DSERVICE_Symbols=0 \
 -DSERVICE_LineNumbers=0 \
 -DSERVICE_Expressions=0"

CFLAGS2="\
 -DENABLE_SymbolsProxy=1 \
 -DENABLE_LineNumbersProxy=1"

CFLAGS3="\
  -DENABLE_DebugContext=0\
  -DENABLE_ELF=0\
  -DSERVICE_StackTrace=0\
  -DSERVICE_Breakpoints=0\
  -DSERVICE_Memory=0\
  -DSERVICE_Registers=0\
  -DSERVICE_RunControl=0\
  -DSERVICE_LineNumbers=0\
  -DSERVICE_Processes=0\
  -DSERVICE_Expressions=0\
  -DSERVICE_MemoryMap=0"


VMS_ALL=`VBoxManage --nologo list vms | sed -e "s/.*{\\(.*\\)}/\\1/"`

HTML=logs/index.tmp
echo "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">" >$HTML
echo "<html>" >>$HTML
echo "<head><title>TCF Nightly Build Status</title></head>" >>$HTML
echo "<body>" >>$HTML
echo "<h1>TCF Nightly Build Status</h1>" >>$HTML

echo "<p>Host: `hostname`</p>" >>$HTML
echo "<p>Date: `date`</p>" >>$HTML
echo "<p>VirtualBox version: `VBoxManage --version`</p>" >>$HTML

echo "<table border=1 cellpadding=8>" >>$HTML
echo "<tr>" >>$HTML
echo "<th>" >>$HTML
echo "IP Addr" >>$HTML
echo "<th>" >>$HTML
echo "Name" >>$HTML
echo "<th>" >>$HTML
echo "Start" >>$HTML
echo "<th>" >>$HTML
echo "Ping" >>$HTML
echo "<th>" >>$HTML
echo "OS" >>$HTML
echo "<th>" >>$HTML
echo "CPU" >>$HTML
echo "<th>" >>$HTML
echo "Build<br>Debug<br>C" >>$HTML
echo "<th>" >>$HTML
echo "Build<br>Debug<br>C++" >>$HTML
echo "<th>" >>$HTML
echo "Build<br>Release<br>C" >>$HTML
echo "<th>" >>$HTML
echo "Build<br>Release<br>C++" >>$HTML
echo "<th>" >>$HTML
echo "Build<br>RPM" >>$HTML
echo "<th>" >>$HTML
echo "Stop" >>$HTML

function start_vm()
{
  local LOGFILE=$HOST-Start.txt
  echo "<td>" >>$HTML
  echo "<a href=\"$LOGFILE\">" >>$HTML
  echo Starting $VM >logs/$LOGFILE
  if VBoxManage --nologo list runningvms | sed -e "s/.*{\\(.*\\)}/\\1/" | grep -q $VM >>logs/$LOGFILE 2>&1 ; then
    echo $VM is already running >>logs/$LOGFILE
    echo "<img src=\"../icons/accept.png\" title=\"OK\"/>" >>$HTML
  elif VBoxManage --nologo startvm $VM >>logs/$LOGFILE 2>&1 ; then
    echo "<img src=\"../icons/accept.png\" title=\"OK\"/>" >>$HTML
  else
    echo "<img src=\"../icons/cross.png\" title=\"Error\"/>" >>$HTML
    SKIP=1
  fi
  echo "</a>" >>$HTML
}

function ping_vm()
{
  local LOGFILE=$HOST-Ping.txt
  echo "<td>" >>$HTML
  echo "<a href=\"$LOGFILE\">" >>$HTML
  echo Ping $VM >logs/$LOGFILE
  sleep 4
  if ping -c 30 $HOST >>logs/$LOGFILE 2>&1 || \
     ping -c 30 $HOST >>logs/$LOGFILE 2>&1
  then
    echo >>logs/$LOGFILE
    if $SSH "ping $PING_FLAG 30 $VBOXHOST" >>logs/$LOGFILE 2>&1 || \
       $SSH "ping $PING_FLAG 30 $VBOXHOST" >>logs/$LOGFILE 2>&1
    then
      if [ "$SET_CLOCK" = 2 ] ; then
        DATE=`date +%m%d%H%M.%S`
        $SSH "/bin/date $DATE" >>logs/$LOGFILE 2>&1
      elif [ ! -z "$SET_CLOCK" ] ; then
        DATE=`date +%m%d%H%M.%S`
        $SSH -tt "sudo /bin/date $DATE" >>logs/$LOGFILE 2>&1
      fi
      if $SSH "cd $TRUNK" >>logs/$LOGFILE 2>&1 ; then
        echo "<img src=\"../icons/accept.png\" title=\"OK\"/>" >>$HTML
      else
        echo "<img src=\"../icons/cross.png\" title=\"SSH cd failed\"/>" >>$HTML
        SKIP=1
      fi
    else
      echo "<img src=\"../icons/cross.png\" title=\"SSH ping failed\"/>" >>$HTML
      SKIP=1
    fi
  else
    echo "<img src=\"../icons/cross.png\" title=\"Ping failed\"/>" >>$HTML
    SKIP=1
  fi
  echo "</a>" >>$HTML
}

function stop_vm()
{
  echo "<td>" >>$HTML
  echo "<a href=\"$HOST-Stop.txt\">" >>$HTML
  echo "Stop $VM" >logs/$HOST-Stop.txt
  if [ -z "$STOP_VM" ] ; then
    echo "VM does not need to be stopped" >>logs/$HOST-Stop.txt
    echo "<img src=\"../icons/accept.png\" title=\"OK\"/>" >>$HTML
  elif VBoxManage --nologo list runningvms | sed -e "s/.*{\\(.*\\)}/\\1/" | grep -q $VM ; then
    if VBoxManage --nologo controlvm $VM savestate >>logs/$HOST-Stop.txt 2>&1 ; then
      echo "<img src=\"../icons/accept.png\" title=\"OK\"/>" >>$HTML
    else
      echo "<img src=\"../icons/cross.png\" title=\"Failed\"/>" >>$HTML
    fi
  else
    echo $VM is already stopped >>logs/$HOST-Stop.txt 2>&1
    echo "<img src=\"../icons/error.png\" title=\"Already stopped\"/>" >>$HTML
  fi
  echo "</a>" >>$HTML
}

function get_make_options()
{
  case $CC in
  gcc)
    if [ -z "$CFLAGS" ] ; then
      echo "OPSYS=$OPSYS CONF=$CONF CFLAGS=-Werror"
    else
      echo "OPSYS=$OPSYS CONF=$CONF 'CFLAGS=-Werror $CFLAGS'"
    fi
    ;;
  g++)
    if [ -z "$CFLAGS" ] ; then
      echo "OPSYS=$OPSYS CONF=$CONF CC=g++ CFLAGS=-Werror"
    else
      echo "OPSYS=$OPSYS CONF=$CONF CC=g++ 'CFLAGS=-Werror $CFLAGS'"
    fi
    ;;
  msvc++)
    if [ -z "$CFLAGS" ] ; then
      echo "OPSYS=$OPSYS CONF=$CONF 'CFLAGS=-x c++'"
    else
      echo "OPSYS=$OPSYS CONF=$CONF 'CFLAGS=-x c++ $CFLAGS'"
    fi
    ;;
  *)
    if [ -z "$CFLAGS" ] ; then
      echo "OPSYS=$OPSYS CONF=$CONF"
    else
      echo "OPSYS=$OPSYS CONF=$CONF 'CFLAGS=$CFLAGS'"
    fi
    ;;
  esac
}

function build_and_start_server()
{
  echo "<td>" >>$HTML
  local LOGFILE=$HOST-$CONF-$CC-Server.txt
  echo "<a href=\"$LOGFILE\">" >>$HTML
  date >logs/$LOGFILE
  echo "$CONF build on $HOST $VM $VMNAME" >>logs/$LOGFILE
  echo "Compiler: $CC" >>logs/$LOGFILE
  echo "Options: `get_make_options`" >>logs/$LOGFILE
  echo >>logs/$LOGFILE
  if $SSH "cd $TRUNK/server; $MAKE `get_make_options` clean all" >>logs/$LOGFILE 2>&1
  then
    echo "<img src=\"../icons/accept.png\" title=\"Server OK\"/>" >>$HTML
    local SERVER_LFILE=$BUILD/logs/server-$HOST.txt
    if [ $OPSYS = Windows ] ; then
      local SERVER_LFILE=`$SSH "cygpath -m $SERVER_LFILE"`
    fi
    $SSH "$TRUNK/server/obj/$OPSYS/$MACHINE/$CONF/server -s TCP::1535 -L$SERVER_LFILE -l0x800" >>logs/$LOGFILE 2>&1 &
  else
    echo "<img src=\"../icons/cross.png\" title=\"Server build failed\"/>" >>$HTML
  fi
  echo "</a>" >>$HTML
}

function stop_server()
{
  local LOGFILE=$HOST-$CONF-$CC-Server.txt
  $SSH "killall server" >>logs/$LOGFILE 2>&1
  if [ -r logs/server-$HOST.txt ] ; then
    echo >>logs/$LOGFILE
    echo "Server log:" >>logs/$LOGFILE
    cat logs/server-$HOST.txt >>logs/$LOGFILE
    rm logs/server-$HOST.txt
    echo "End of server log" >>logs/$LOGFILE
  fi
}

function build_and_test_agent()
{
  # Currently we cannot test login feature of Terminals service
  if [ -z "$CFLAGS" ] ; then
    CFLAGS=-DTERMINALS_NO_LOGIN=1
  else
    CFLAGS="-DTERMINALS_NO_LOGIN=1 $CFLAGS"
  fi

  local LOGFILE=$HOST-$CONF-$CC-Agent-$SEQ.txt
  echo "<a href=\"$LOGFILE\">" >>$HTML
  date >logs/$LOGFILE
  echo "$CONF build on $HOST $VM $VMNAME" >>logs/$LOGFILE
  echo "Compiler: $CC" >>logs/$LOGFILE
  echo "Options: `get_make_options`" >>logs/$LOGFILE
  echo >>logs/$LOGFILE
  if $SSH "cd $TRUNK/agent; $MAKE `get_make_options` clean all" >>logs/$LOGFILE 2>&1
  then
    local AGENT_LFILE=$BUILD/logs/agent-$HOST.txt
    if [ $OPSYS = Windows ] ; then
      local AGENT_LFILE=`$SSH "cygpath -m $AGENT_LFILE"`
    fi
    $SSH "$TRUNK/agent/obj/$OPSYS/$MACHINE/$CONF/agent -s TCP::1534 -L$AGENT_LFILE -l0" >>logs/$LOGFILE 2>&1 &
    sleep 15
    TESTURL1=ID=Test-Agent-$HOST-$SEQ:TransportName=TCP:Host=$HOST:Port=1534
    TESTURL2=ID=Test-Proxy-$HOST-$SEQ:TransportName=TCP:Host=$HOST:Port=1535
    echo >>logs/$LOGFILE
    echo "Starting tests, target: $TESTURL1" >>logs/$LOGFILE
    if time -p java -ea \
      -classpath java-bin \
      org.eclipse.tm.internal.tcf.debug.tests.Main \
      $TESTURL1 \
      >>logs/$LOGFILE 2>&1
    then
      if [ "$OPSYS" = Windows -a ! -z "$CFLAGS" ] ; then
        # TCF server does not support PE object files
        if [ -s logs/agent-$HOST.txt ]
        then
          echo "<img src=\"../icons/error.png\" title=\"Agent log is not empty\"/>" >>$HTML
        else
          echo "<img src=\"../icons/accept.png\" title=\"Agent OK\"/>" >>$HTML
        fi
      else
        echo >>logs/$LOGFILE
        echo "Starting tests, target: $TESTURL2 $TESTURL1" >>logs/$LOGFILE
        if time -p java -ea \
          -classpath java-bin \
          org.eclipse.tm.internal.tcf.debug.tests.Main \
          $TESTURL2 $TESTURL1 \
          >>logs/$LOGFILE 2>&1
        then
          if [ -s logs/agent-$HOST.txt ]
          then
            echo "<img src=\"../icons/error.png\" title=\"Agent log is not empty\"/>" >>$HTML
          else
            echo "<img src=\"../icons/accept.png\" title=\"Agent OK\"/>" >>$HTML
          fi
        else
          echo "<img src=\"../icons/cancel.png\" title=\"Agent/Server test failed\"/>" >>$HTML
        fi
      fi
    else
      echo "<img src=\"../icons/cancel.png\" title=\"Agent test failed\"/>" >>$HTML
    fi
    $SSH "killall agent" >>logs/$LOGFILE 2>&1
    if [ -r logs/agent-$HOST.txt ] ; then
      echo >>logs/$LOGFILE
      echo "Agent log:" >>logs/$LOGFILE
      cat logs/agent-$HOST.txt >>logs/$LOGFILE
      rm logs/agent-$HOST.txt
      echo "End of agent log" >>logs/$LOGFILE
    fi
  else
    echo "<img src=\"../icons/cross.png\" title=\"Agent build failed\"/>" >>$HTML
  fi
  echo "</a>" >>$HTML
  sleep 5
  $SSH "cd $TRUNK/agent; rm -rf obj" >>logs/$LOGFILE 2>&1
}

function build_rpm()
{
  echo "<td>" >>$HTML
  echo "<a href=\"$HOST-RPM.txt\">" >>$HTML
  echo RPM build on $VM >logs/$HOST-RPM.txt
  if [ -z "$BUILD_RPM" ] ; then
    echo "<img src=\"../icons/error.png\" title=\"Not supported\"/>" >>$HTML
  elif $SSH "cd $TRUNK/agent; $MAKE clean rpm" >>logs/$HOST-RPM.txt 2>&1 ; then
    echo "<img src=\"../icons/accept.png\" title=\"OK\"/>" >>$HTML
  else
    echo "<img src=\"../icons/cross.png\" title=\"Failed\"/>" >>$HTML
  fi
  echo "</a>" >>$HTML
}

for VM in $VMS_ALL
do
  echo "<tr>" >>$HTML
  if grep -q $VM vms.lst ; then
    SKIP=
    HOST=`grep $VM vms.lst | sed -e "s/.*:\\(.*\\)/\\1/"`
    VMNAME=`VBoxManage --nologo showvminfo $VM --machinereadable | grep name= | sed -e "s/name=\"\(.*\)\"/\1/"`
    SSH="ssh -o TCPKeepAlive=yes $VBOXUSER@$HOST"

    echo "<th>" >>$HTML
    echo "$HOST" >>$HTML
    echo "<td>" >>$HTML
    echo "$VMNAME" >>$HTML

    start_vm
    if [ ! -z "$SKIP" ] ; then
      continue
    fi

    BUILD=/net/$VBOXHOST/home/virtualbox/build
    TRUNK=$BUILD/trunk
    MAKE=make
    PING_FLAG=-c
    OPSYS_FLAG=-o
    BUILD_RPM=
    STOP_VM=
    SET_CLOCK=

    case $HOST in
    192.168.155.4)
      # Ubuntu
      STOP_VM=1
      SET_CLOCK=
      ;;
    192.168.155.5)
      # Free BSD
      MAKE=gmake
      OPSYS_FLAG=-s
      STOP_VM=1
      ;;
    192.168.155.10)
      # Windows 7 32
      PING_FLAG=-n
      SET_CLOCK=2
      ;;
    192.168.155.11)
      # Windows 7 64
      PING_FLAG=-n
      SET_CLOCK=2
      ;;
    *)
      # Linux
      STOP_VM=1
      SET_CLOCK=1
      ;;
    esac

    ping_vm
    if [ ! -z "$SKIP" ] ; then
      continue
    fi

    OPSYS=`$SSH "uname $OPSYS_FLAG"` || exit 1
    MACHINE=`$SSH "uname -m"` || exit 1
    $SSH "killall server" >/dev/null 2>&1
    $SSH "killall agent" >/dev/null 2>&1

    if [ "$OPSYS" = Cygwin ] ; then
      OPSYS=Windows
      echo "<td>" >>$HTML
      echo "$OPSYS" >>$HTML
      echo "<td>" >>$HTML
      echo "$MACHINE" >>$HTML

      for CONF in Debug Release
      do
        for CC in msvc msvc++
        do

          CFLAGS=
          build_and_start_server

          SEQ=1
          for CFLAGS in "" "$CFLAGS1" "$CFLAGS2" "$CFLAGS3"
          do
            build_and_test_agent
            SEQ=`expr $SEQ + 1`
          done

          stop_server

          sleep 5
        done
      done

      OPSYS=Cygwin
      echo "<tr>" >>$HTML
      echo "<td colspan=\"4\">" >>$HTML
    fi

    echo "<td>" >>$HTML
    echo "$OPSYS" >>$HTML
    echo "<td>" >>$HTML
    echo "$MACHINE" >>$HTML

    for CONF in Debug Release
    do
      for CC in gcc g++
      do

        CFLAGS=
        build_and_start_server

        SEQ=1
        for CFLAGS in "" "$CFLAGS1" "$CFLAGS2" "$CFLAGS3"
        do
          build_and_test_agent
          SEQ=`expr $SEQ + 1`
        done

        stop_server

        sleep 5
      done
    done

    build_rpm

    $SSH "sync" || exit 1
    sleep 5
    stop_vm
  else
    echo "<th>" >>$HTML
    echo "Not in vms.lst" >>$HTML
    echo "<td>" >>$HTML
    echo "$VM"  >>$HTML
  fi

done

#killall VirtualBox || exit 1


echo "</table>" >>$HTML
echo "<p>Finished at: `date`</p>" >>$HTML
echo "</body>" >>$HTML
echo "</html>" >>$HTML

mv $HTML logs/index.html || exit 1
