/*
  WAVEFORMATEX.java

  (c) 2010-2011 Edward Swartz

  All rights reserved. This program and the accompanying materials
  are made available under the terms of the Eclipse Public License v1.0
  which accompanies this distribution, and is available at
  http://www.eclipse.org/legal/epl-v10.html
 */
package ejs.base.winmm;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class WAVEFORMATEX extends Structure<WAVEFORMATEX, WAVEFORMATEX.ByValue, WAVEFORMATEX.ByReference> {
	public short wFormatTag;
	public short nChannels;
	public int nSamplesPerSec;
	public int nAvgBytesPerSec;
	public short nBlockAlign;
	public short wBitsPerSample;
	public short cbSize;
	public WAVEFORMATEX() {
		super();
	}
	public WAVEFORMATEX(short wFormatTag, short nChannels, int nSamplesPerSec, int nAvgBytesPerSec, short nBlockAlign, short wBitsPerSample, short cbSize) {
		super();
		this.wFormatTag = wFormatTag;
		this.nChannels = nChannels;
		this.nSamplesPerSec = nSamplesPerSec;
		this.nAvgBytesPerSec = nAvgBytesPerSec;
		this.nBlockAlign = nBlockAlign;
		this.wBitsPerSample = wBitsPerSample;
		this.cbSize = cbSize;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected WAVEFORMATEX newInstance() { return new WAVEFORMATEX(); }
	public static WAVEFORMATEX[] newArray(int arrayLength) {
		return Structure.newArray(WAVEFORMATEX.class, arrayLength);
	}
	public static class ByReference extends WAVEFORMATEX implements Structure.ByReference {}
	public static class ByValue extends WAVEFORMATEX implements Structure.ByValue {}
}
