package ejs.base.winmm;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class WAVEFORMAT extends Structure<WAVEFORMAT, WAVEFORMAT.ByValue, WAVEFORMAT.ByReference> {
	public short wFormatTag;
	public short nChannels;
	public int nSamplesPerSec;
	public int nAvgBytesPerSec;
	public short nBlockAlign;
	public WAVEFORMAT() {
		super();
	}
	public WAVEFORMAT(short wFormatTag, short nChannels, int nSamplesPerSec, int nAvgBytesPerSec, short nBlockAlign) {
		super();
		this.wFormatTag = wFormatTag;
		this.nChannels = nChannels;
		this.nSamplesPerSec = nSamplesPerSec;
		this.nAvgBytesPerSec = nAvgBytesPerSec;
		this.nBlockAlign = nBlockAlign;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected WAVEFORMAT newInstance() { return new WAVEFORMAT(); }
	public static WAVEFORMAT[] newArray(int arrayLength) {
		return Structure.newArray(WAVEFORMAT.class, arrayLength);
	}
	public static class ByReference extends WAVEFORMAT implements Structure.ByReference {}
	public static class ByValue extends WAVEFORMAT implements Structure.ByValue {}
}
