/* Automatically generated by po2tbl.sed from v9t9.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"\
spritechanges: %08X\n\
\n", 2},
  {"Sprite %02d changed: %s%s%s\n", 3},
  {"pos, ", 4},
  {"color, ", 5},
  {"patt", 6},
  {"Deleted sprites past %d\n", 7},
  {"Updating sprite %d because undeleted\n", 8},
  {"Updating sprite %d because deleted\n", 9},
  {"Sprite %d changed pattern\n", 10},
  {"VDP_CHANGES.SPRITE: %04X  DELBITMAP: %04X/%04X\n", 11},
  {"No deleted sprites\n", 12},
  {"redrawing char %d due to deleted sprite\n", 13},
  {"Five sprites on lines:\n", 14},
  {"going to redraw sprite %d at %d,%d\n", 15},
  {"Toredraw: %08X  spritechanges: %08X\n", 16},
  {"redrawing char %d due to moved/deleted sprite\n", 17},
  {"\
screenchanges:\n\
\t", 18},
  {"Sprite at (%d,%d) intersects (%d,%d)\n", 19},
  {"Redrawing sprite #%d [%d,%d,%02x,%02x]\n", 20},
  {"Setting graphics mode\n", 21},
  {"Setting text mode\n", 22},
  {"testing console video... ", 23},
  {"cannot access.\n", 24},
  {"ok.\n", 25},
  {"SVGAlib Options", 26},
  {"These commands control the SVGAlib interface", 27},
  {"Set the video mode used in SVGAlib", 28},
  {"video mode", 29},
  {"detecting mode %d... ", 30},
  {"\n", 31},
  {"no suitable VGA modes found.\n", 32},
  {"succeeded.\n", 33},
  {"testing mode %d... ", 34},
  {"success.\n", 35},
  {"cannot use this mode.\n", 36},
  {"Could not restore video mode for SVGAlib\n", 37},
  {"Shutting down video... ", 38},
  {"done.\n", 39},
  {"could not open audio (%s)\n", 40},
  {"could not open stream (%s)\n", 41},
  {"\
\n\
warning, this module is not optimal and\n\
sound can be delayed up to a second.\n\
Consider killing esd and using native OSS or ALSA sound.\n\
\n", 42},
  {"Could not open Enlightened Sound Daemon:  %s\n", 43},
  {"disable: %d\n", 44},
  {"RS232/%d is %s\n", 45},
  {"RS232/%d cannot be assigned to a device\n", 46},
  {"RS232/%d cannot be used (%s)\n", 47},
  {"Linux-RS232: could not assign any serial ports\n", 48},
  {"\
could not assign %d serial ports, only RS232/1 through RS232/%d are \
available\n", 49},
  {"assigned %d serial ports\n", 50},
  {"Could not open %s\n", 51},
  {"failure in select() in My_RS232_Interrupt\n", 52},
  {"... data ready for reading\n", 53},
  {"... data ready to write\n", 54},
  {"... data exception\n", 55},
  {"cannot read modem lines\n", 56},
  {"** Interrupt **\n", 57},
  {"Trying to receive %d chars\n", 58},
  {"most=%d, max=%d\n", 59},
  {"select passed, max = %d\n", 60},
  {"received %d chars of %d maximum\n", 61},
  {"sent %d chars\n", 62},
  {"could not set RTS/DSR lines\n", 63},
  {"could not set attributes (%s)\n", 64},
  {"unsupported baud rate %d, using 50\n", 65},
  {"could not set input baud rate of %d\n", 66},
  {"Input baud rate:  %d\n", 67},
  {"could not set output baud rate of %d\n", 68},
  {"Output baud rate:  %d\n", 69},
  {"Setting CTRL register to %04X\n", 70},
  {"Setting INVL register to %04X\n", 71},
  {"Setting RCVRATE register to %04X\n", 72},
  {"Setting XMITRATE register to %04X\n", 73},
  {"Setting control bits to %04X\n", 74},
  {"Transmitting char %02X (%c)\n", 75},
  {"RS232/%d write error\n", 76},
  {"Reading status bits as %08X\n", 77},
  {"Receiving char %02X (%c)\n", 78},
  {"Could not create image for window\n", 79},
  {"cannot handle bits_per_pixel of %d\n", 80},
  {"dirtying rectangle (%d,%d+%d,%d)\n", 81},
  {"Resize: vwxsz = %d, vwysz = %d\n", 82},
  {"Setting index %d to color %d\n", 83},
  {"Index is normal color\n", 84},
  {"Index is fg/bg color changing\n", 85},
  {"no compatible color classes found, cannot display\n", 86},
  {"video_X:  Cannot use visual with only %d colors.\n", 87},
  {"color class = %s\n", 88},
  {"Detected X Window System...\n", 89},
  {"cannot allocate size hints\n", 90},
  {"failed in XCreateWindow\n", 91},
  {"Could not create GC for window\n", 92},
  {"could not allocate color %d\n", 93},
  {"color #%d:  got named color '%s'\n", 94},
  {"color #%d:  got RGB color\n", 95},
  {"Could not allocate 2 read/write colorcells\n", 96},
  {"alloced = %d\n", 97},
  {"allocated custom colormap for window\n", 98},
  {"X_video_updatelist (%d,%d+%d,%d)\n", 99},
  {"Got color %d (%x)\n", 100},
  {"Drew %d rects, %d pixels\n", 101},
  {"%d/%d solid\n", 102},
  {"testing console keyboard... ", 103},
  {"Opening console keyboard... ", 104},
  {"could not open console!\n", 105},
  {"setting raw mode\n", 106},
  {"Cannot get keyboard mode.\n", 107},
  {"restart[ed] (%d, %d)...\n", 108},
  {"restop (%d, %d)...\n", 109},
  {"disable... (%d, %d)\n", 110},
  {"Releasing keyboard...\n", 111},
  {"switched_back\n", 112},
  {"switched_away\n", 113},
  {"orig_acqsig = %p, vt.acqsig = %d\n", 114},
  {"retrieving keycode for %d = ", 115},
  {"%d\n", 116},
  {"not mapped\n", 117},
  {"function key\n", 118},
  {"Unknown function keycode %04X\n", 119},
  {"special key\n", 120},
  {"Unknown special keycode %04X\n", 121},
  {"cursor key\n", 122},
  {"Unknown cursor keycode %04X\n", 123},
  {"shift key\n", 124},
  {"Unknown shift keycode %04X\n", 125},
  {"Latin key %c [%02X]\n", 126},
  {"kblatin:  Got strange latin key %d\n", 127},
  {"kblatin:  Unprogrammed fake key '%c' (%d)\n", 128},
  {"keypad key\n", 129},
  {"Unknown keycode %04X\n", 130},
  {"Unknown scancode %d\n", 131},
  {"Mouse: (%d,%d,%d)\n", 132},
  {"got %d chars to read...\n", 133},
  {"scan: %02X\n", 134},
  {"Key: S:%d O:%d T:%d V:%d\n", 135},
  {"params setup error: %s\n", 136},
  {"cannot set up period size: %s\n", 137},
  {"params setting error: %s\n", 138},
  {"error preparing PCM handle\n", 139},
  {"record info error: %s\n", 140},
  {"device supports recording range %d to %d Hzclipping default rate.\n", 141},
  {"device does not support desired eight-bit recording format\n", 142},
  {"device cannot set recording format\n", 143},
  {"\
device cannot set requested PCM recording parameters:\n\
%s\n", 144},
  {"StopSoundRecording:  Closing previously recording soundtrack\n", 145},
  {"RecordSoundToFile:  could not open '%s' for appending", 146},
  {"PausingSoundRecording:  %s\n", 147},
  {"paused", 148},
  {"resuming", 149},
  {"RecordSoundToFile:  using '%s'\n", 150},
  {"ALSA Sound Mixer Options", 151},
  {"These commands control the ALSA 99/4A sound module", 152},
  {"Specify ALSA PCM drivere", 153},
  {"device", 154},
  {"device to use for PCM sound; e.g. 'plughw:0,0' ", 155},
  {"Record soundtrack to a file", 156},
  {"file", 157},
  {"\
file to receive sound; if file exists, new data will be appended to it; if \
no extension is given, one will be added that details the RAW sound format \
used", 158},
  {"Pause or resume soundtrack recording (does not close sound file)", 159},
  {"state", 160},
  {"whether recording is paused", 161},
  {"Stop soundtrack recording and close sound file", 162},
  {"Could not open ALSA PCM device (%s): %s\n", 163},
  {"key = 0x%X\n", 164},
  {"direct key\n", 165},
  {"no symbol for keycode (%d)\n", 166},
  {"ioctl failed (", 167},
  {"desired sound quality not supported by hardware (%08X/%08X)\n", 168},
  {"Detected Open Sound System...\n", 169},
  {"Could not open /dev/dsp:  %s\n", 170},
  {"cannot open sound (%s)\n", 171},
  {"speaker_poll\n", 172},
  {"speaker_poll:  next=%d, v->volume=%d, v->hertz=%d\n", 173},
  {"Detected PC speaker..\n", 174},
  {"PC Speaker Options", 175},
  {"These commands control the PC speaker sound module", 176},
  {"Set base rate for arpeggiation", 177},
  {"Hz", 178},
  {"changes per second", 179},
  {"Could not open console for sound effects (%s)\n", 180},
  {"No Win32 wave sound devices installed\n", 181},
  {"out of memory for wave headers\n", 182},
  {"could not create wave semaphore\n", 183},
  {"Could not create mixer event\n", 184},
  {"could not create mixer thread, '%d'\n", 185},
  {"Could not open a wave device.\n", 186},
  {"failed in waveOutPrepareHeader (%d)\n", 187},
  {"win32keyboard_scan: key is %d [%d]\n", 188},
  {"unknown keycode %d\n", 189},
  {"could not assign any serial ports\n", 190},
  {"\
could not assign %d serial ports,\n\
only RS232/1 through RS232/%d are available\n", 191},
  {"opening RS232 port", 192},
  {"setting comm buffers", 193},
  {"getting comm state", 194},
  {"setting comm state", 195},
  {"setting comm mask", 196},
  {"setting timeouts", 197},
  {"creating RS232 mutex", 198},
  {"creating RS232 monitor thread", 199},
  {"... interrupt: data ready for reading\n", 200},
  {"... line change\n", 201},
  {"\
Commit_Changes: BaudRate=%d, fParity=%d, ByteSize=%d, Parity=%d, StopBits=%\
d\n", 202},
  {"committing RS232 state changes", 203},
  {"setting RTS", 204},
  {"setting break", 205},
  {"Baud rate:  %d\n", 206},
  {"*- Interrupt -*\n", 207},
  {"RS232/%d write error (%s)\n", 208},
  {"RS232/%d read error (%s)\n", 209},
  {"video_restore: could not restore bitmap %8X\n", 210},
  {"video_restore: could not restore primary %8X\n", 211},
  {"SetCooperativeLevel failed (%d)\n", 212},
  {"SetDisplayMode\n", 213},
  {"SetEntries failed (%d)\n", 214},
  {"SetCooperativeLevel (DDSCL_NORMAL)", 215},
  {"RegisterClass szVideoClassName", 216},
  {"V9t9-on-a-Monitor", 217},
  {"could not create window\n", 218},
  {"error in Lock with %8X\n", 219},
  {"videoupdatepalette:  SetPalette failed (%d)\n", 220},
  {"CreateSurface (%d)\n", 221},
  {"CreateSurface (screen)", 222},
  {"GetAttachedSurface (screen)", 223},
  {"CreateSurface (offscreen)", 224},
  {"CreatePalette failed", 225},
  {"deo failed (%d)\n", 226},
  {"RegisterClass szWindowClassName", 227},
  {"RegisterClass szStatusClassName", 228},
  {"V9t9-in-a-Box", 229},
  {"V9t9 Status", 230},
  {"Refresh rate: %d pixels/frame, %1.2f (%d) frames/second\n", 231},
  {"Update: %d,%d %d,%d\n", 232},
  {"could not do SetWindowPos (%d)\n", 233},
  {"drawdib paint\n", 234},
  {"drawdib painting\n", 235},
  {"Win32 DrawDIB Commands", 236},
  {"These options control the behavior of the V9t9-in-a-Window module", 237},
  {"Toggle direct painting of windows versus waiting for a WM_PAINT message", 238},
  {"on:  draw as soon as possible; off:  queue updates for WM_PAINT", 239},
  {"Could not find GTK main window!\n", 240},
  {"could not find a spare page file for '%s' (page=%d)", 241},
  {"could not create page file '%s'", 242},
  {"could not write file '%s' (%s)", 243},
  {"error writing to PIO (%s) (%s)", 244},
  {"\
handling code %d\n\
\n", 245},
  {"unsupported operation %d on PIO/%d\n", 246},
  {"doing operation %d on PIO/%d\n", 247},
  {"PIO DSR Options", 248},
  {"These commands control the parallel port (PIO) emulation", 249},
  {"Give local name for PIO output", 250},
  {"filename", 251},
  {"\
filename for printer pages under V9t9DataDir; use a printf-style specifier \
to number separate pages (e.g. 'page%03d.out')", 252},
  {"\
Name of emulated PIO DSR ROM image which fits in the CPU address space \
>4000...>5FFF", 253},
  {"name of binary image", 254},
  {"setting up PIO DSR ROM\n", 255},
  {"PIO DSR ROM", 256},
  {"GTK key = %02X (%d)\n", 257},
  {"create_xshm_image failed\n", 258},
  {"apple2: internal colormap allocation error\n", 259},
  {"Can't figure out color space\n", 260},
  {"Composite mode initialized\n", 261},
  {"Composite video not supported on this OS\n", 262},
  {"GTK Video Options", 263},
  {"These commands control the GTK video emulation", 264},
  {"Use composite video filter (borrowed from Apple2 BSOD hack)", 265},
  {"on:  use composite mode; off:  use pixel-for-pixel display", 266},
  {"Set tint level for composite video", 267},
  {"level", 268},
  {"tint level (0..359)", 269},
  {"Set brightness level for composite video", 270},
  {"brightness level (0..100)", 271},
  {"Set color level for composite video", 272},
  {"color level (0..100)", 273},
  {"Set contrast level for composite video", 274},
  {"contrast level (0..100)", 275},
  {"Dump screen info", 276},
  {"Could not allocate 15 colors\n", 277},
  {"Got writeable colors for bg/fg\n", 278},
  {"No writeable colors available\n", 279},
  {"Color %d is %08X\n", 280},
  {"Could not get visual\n", 281},
  {"Could not get image\n", 282},
  {"No sound driver loaded\n", 283},
  {"No video driver loaded\n", 284},
  {"%.*s: got PAB error %d [%s (%s)]\n", 285},
  {"%.*s:  existing PAB not closed\n", 286},
  {"\
PAB contents: flags=>%02X, reclen=%d, addr=>%04X, charcount=%d, recnum=%d\n", 287},
  {"PAB contents: addr=>%04X, charcount=%d, recnum=%d\n", 288},
  {"got subroutine error %d\n", 289},
  {"got subroutine error %d [%s (%s)]\n", 290},
  {"filename in FDR doesn't match filename ('%.*s' | '%.*s')\n", 291},
  {"DSKcomparefdrandpab:  record length differs\n", 292},
  {"DSKcomparefdrandpab:  var + relative file\n", 293},
  {"DSKcomparefdrandpab: fixed/variable flag differs\n", 294},
  {"file type mismatch on file open", 295},
  {"DSKcomparefdrandsub:  filenames don't match ('%.*s' | '%.*s')\n", 296},
  {"reading sector %d", 297},
  {"writing sector %d", 298},
  {"getfilespec_pab:  pab len = %d\n", 299},
  {"getfilespec_pab:  length of device 0x8354 = %04X\n", 300},
  {"bad characters in filename", 301},
  {"couldn't make spec", 302},
  {"trying to match '%s'\n", 303},
  {"Re-reading catalog for DSK%d\n", 304},
  {"couldn't open directory for catalog", 305},
  {"reading catalog entry\n", 306},
  {"DSKreadcatalog: reached end of directory\n", 307},
  {"no free files", 308},
  {"can't have variable record size of 255", 309},
  {"bad catalog open flags", 310},
  {"can't append to FIXED file", 311},
  {"could not open for update", 312},
  {"read FDR successfully\n", 313},
  {"setting up new FDR\n", 314},
  {"could not open for output", 315},
  {"could not open for input", 316},
  {"DSKRead:  error due to not finding open file", 317},
  {"read from append/output file", 318},
  {"dump of catalog record:", 319},
  {"DSKWrite:  error due to not finding open file", 320},
  {"writing to input file", 321},
  {"writing to catalog", 322},
  {"DSKSeek:  error due to not finding open file", 323},
  {"DSKSeek:  error due to seeking catalog", 324},
  {"append/output mode can't seek", 325},
  {"can't open catalog as binary", 326},
  {"trying to open binary image\n", 327},
  {"read %d bytes to >%04X\n", 328},
  {"can't save catalog as binary", 329},
  {"trying to save binary image\n", 330},
  {"can't delete catalog", 331},
  {"trying to delete file\n", 332},
  {"deleting file\n", 333},
  {"DSKStatus:  EOF on variable file", 334},
  {"DSKStatus:  EOF on fixed file\n", 335},
  {"DSKStatus:  no PAB file yet...\n", 336},
  {"DSKStatus:  file not found\n", 337},
  {"DSKStatus:  catalog status\n", 338},
  {"DSKStatus:  opening file\n", 339},
  {"DSKStatus:  file was open\n", 340},
  {"\
DSKStatus:  flags=%02X\n\
\n", 341},
  {"creating catalog sector 0\n", 342},
  {"creating catalog sector 1\n", 343},
  {"creating catalog directory sector %d\n", 344},
  {"ignoring sector write request", 345},
  {"could not open to modify protection", 346},
  {"could not open to modify filename", 347},
  {"\
Renamed '%s' to '%s'\n\
\n\
\n", 348},
  {"could not open to read sectors", 349},
  {"\
reading %d sectors from sector #%d from file, storing to >%04X\n\
\n", 350},
  {"DskDirectInput:  Could not seek to sector", 351},
  {"DskDirectInput:  Could not read sectors", 352},
  {"could not open to write sectors", 353},
  {"Setting size of '%s' to %d sectors\n", 354},
  {"\
writing %d sectors at sector #%d to file, reading from >%04X\n\
\n", 355},
  {"\
The current program is attempting to control the disk controller,\n\
but this functionality does not work with the emulated disk DSR.\n\
Consider running this application from a disk-on-a-disk (DOAD).\n", 356},
  {"emu disk DSR on\n", 357},
  {"\
DSR Read >4000 = >%2X\n\
\n", 358},
  {"emu disk DSR off\n", 359},
  {"\
code = %d\n\
\n", 360},
  {"passing control to real disk", 361},
  {"passing control to real disk\n", 362},
  {"did not match DSK.%.*s\n", 363},
  {"matched DSK.%.*s on DSK%d\n", 364},
  {"doing operation %d on DSK%d\n", 365},
  {"doing operation %d on DSK%d [%d, %04X, %04X]\n", 366},
  {"ignoring code = %d\n", 367},
  {"error in emudisk_config_files", 368},
  {"Invalid file number\n", 369},
  {"Invalid file name '%s'\n", 370},
  {"Could not reopen catalog at '%s'\n", 371},
  {"Could not reopen file '%s'\n", 372},
  {"Unrecognized file field: %d\n", 373},
  {"DSK%d (%s) is inaccessible when real (DOAD) disk DSR is loaded\n", 374},
  {"Emulated Disk DSR Options", 375},
  {"\
These commands control the emulated files-in-a-directory (FIAD) emulation", 376},
  {"Set DSK1 directory", 377},
  {"dir", 378},
  {"directory containing V9t9 files", 379},
  {"Set DSK2 directory", 380},
  {"Set DSK3 directory", 381},
  {"Set DSK4 directory", 382},
  {"Set DSK5 directory", 383},
  {"\
Name of emulated DSR ROM image which fits in the CPU address space >4000...\
>5FFF; this DSR defines DSK1 through DSK5", 384},
  {"\
Name of emulated DSR ROM image which fits in the CPU address space >4000...\
>5FFF; this DSR defines DSK3 through DSK5 and can share space with the real \
(DOAD) disk DSR", 385},
  {"Toggle preservation of original file type (V9t9 or TIFILES)", 386},
  {"\
on: don't change existing file's type; off: change type to NewFileFormat", 387},
  {"Select type for new files or converted files", 388},
  {"v9t9: original V9t9 file type; tifiles: TIFILES (XMODEM) format", 389},
  {"\
Toggle treatment of unknown (non-V9t9 and non-TIFILES) files as DOS/Unix/Mac \
text files", 390},
  {"on:  read unknown file as text; off:  generate error", 391},
  {"\
Allow catalogs read through DSKx. to return more than 127 records; some \
programs may depend on this limit", 392},
  {"on: allow up to 32767 entries, off: restrict to 127 entries", 393},
  {"\
Repair files with bad file sizes, even when opened read-only.  This is a bit \
dangerous if you try to open a non-V9t9 file, which will (obviously) appear \
damaged.  V9t9 will try to rule out files that don't pass enough sanity \
checks, though.", 394},
  {"on: repair damaged files, off: leave them alone", 395},
  {"\
Rename older V9t9 files which were mangled to fit in the DOS 8.3 filename \
format.  These files were split at the 8th character with a '.' and all \
illegal DOS characters (", 396},
  {"on: rename old V9t9 files, off: leave them alone", 397},
  {"\
Generate filenames that conform to the old V9t9 DOS-mangled format (see \
above) instead of the new format. Not recommended unless you actively use \
the DOS version.", 398},
  {"on: generate old V9t9 filenames, off: generate current V9t9 filenames", 399},
  {"Top address used in VDP RAM", 400},
  {"address", 401},
  {"VDP RAM address, minus one", 402},
  {"file number", 403},
  {"index of files[] array", 404},
  {"name of field in pab_tifile to save", 405},
  {"field contents", 406},
  {"contents of field", 407},
  {"setting up emulated disk DSR ROM\n", 408},
  {"Emulated disk DSR ROM", 409},
  {"loadctrl=%1X\t\n", 410},
  {"\
ctrl=%02X\n\
rcl0=%d,rcl1=%d, clk4m=%d, Podd=%d,Penb=%d, SBS2=%d,SBS1=%d\t", 411},
  {"invl=%03X\t", 412},
  {"rcvrate=%03X\t", 413},
  {"xmitrate=%03X\t", 414},
  {"txchar=%02X (%c)\t", 415},
  {"recvbps=%d, xmitbps=%d\n", 416},
  {"Write buffer: %d/%d  Read buffer: %d/%d\n", 417},
  {"*** Interrupt ***\n", 418},
  {"\
Buffering char %02X (%c)\n\
\n", 419},
  {"Received char %02X (%c)\n", 420},
  {"*** Flushing buffers", 421},
  {"*** Transmit buffer was not empty\n", 422},
  {"\
Calc_BPS_Rate:  *bps = %d\n\
\n", 423},
  {"RealRS232_0_10_w: %d / %d\n", 424},
  {"RealRS232_11_14_w: %d / %d\n", 425},
  {"RealRS232_16_21_w: %d / %d\n", 426},
  {"RealRS232_0_7_r: %04X / %d\n", 427},
  {"RealRS232_9_31_r: %d / %d\n", 428},
  {"RealRS232_Reset_w: %d\n", 429},
  {"TI RS232 DSR Options", 430},
  {"These commands control the TI RS232 emulation", 431},
  {"Give local name for first RS232 port", 432},
  {"filename or device for current operating system", 433},
  {"Give local name for second RS232 port", 434},
  {"\
Name of RS232 DSR ROM image which fits in the CPU address space >4000...>5FFF", 435},
  {"setting up TI RS232 DSR ROM\n", 436},
  {"TI RS232 DSR ROM", 437},
  {"DOAD server:  cannot get %d bytes for disk image '%s' (%s)\n", 438},
  {"DOAD server:  cannot write disk header for image '%s' (%s)\n", 439},
  {"DOAD server:  cannot read disk header for image '%s' (%s)\n", 440},
  {"\
DOAD server:  disk image '%s' has unknown type (got '%*s', expected '%*s')\n", 441},
  {"DOAD server:  disk image '%s' has too new version (%d > %d)\n", 442},
  {"DOAD server:  cannot get info about disk image '%s' (%s)\n", 443},
  {"DOAD server:  cannot read sector 0 for '%s' (%s)\n", 444},
  {"Disk image has too large track size (%d > %d)\n", 445},
  {"DOAD server:  creating new disk image at DSK%d (%s)\n", 446},
  {"DOAD server:  could not create disk (%s)\n", 447},
  {"FDCopendisk\n", 448},
  {"Cannot access disk '%s' (%s)\n", 449},
  {"\
Opened %s disk '%s' #%d,\n\
#tracks=%d, tracksize=%d, sides=%d\n", 450},
  {"DSK.handle=%d\n", 451},
  {"Buffer contents:\n", 452},
  {"writing %d bytes of data on track %d, trackoffset = %d, offset = %d\n", 453},
  {"DOAD server:  could not seek disk '%s' to byte %d (%s)\n", 454},
  {"\
DOAD server:  could not write %d bytes of data to disk '%s' at byte %d (%s)\n", 455},
  {"retrying for id marker (CRC=%04X != %04X)\n", 456},
  {"Formatting sector track:%d, side:%d, sector:%d, size:%d, crc=%04X\n", 457},
  {"\
Program is formatting track on '%s' with non-ordinary sectors;\n\
this does not work with sector-image disks", 458},
  {"retrying for sector data (CRC=%04X != %04X)\n", 459},
  {"Lost sector data in format of sector-image disk '%s'\n", 460},
  {"DOAD server:  disk image '%s' is write-protected\n", 461},
  {"Inconsistent idoffset (%d)", 462},
  {"Inconsistent dataoffset (%d)", 463},
  {"FDChold on\n", 464},
  {"FDChold off\n", 465},
  {"FDCclosedisk\n", 466},
  {"cannot seek past end of disk Tr%d(%d) Sd%d(%d)\n", 467},
  {"seeking to Tr%d Sd%d = byte %d of file\n", 468},
  {"failed to seek!\n", 469},
  {"Reading data from track %d\n", 470},
  {"failed to read track %d data\n", 471},
  {"FDC seek home\n", 472},
  {"FDC seek, T%d s%d\n", 473},
  {"FDC seek, record mismatch (%d != %d) %d\n", 474},
  {"FDC step in, T%d s%d\n", 475},
  {"FDC find ID marker\n", 476},
  {"\
FDCfindIDmarker: starting at %d, traversing [%d...%d) (track offset: %d)\n", 477},
  {"FDCfindIDmarker: failed ID CRC check (%04X != %04X)\n", 478},
  {"FDCfindIDmarker: T%d, S%d, s%d\n", 479},
  {"FDCfindIDmarker: found marker at offset >%04X\n", 480},
  {"FDCfindIDmarker: noop success\n", 481},
  {"FDC match ID marker: looking for T%d, S%d\n", 482},
  {"unmatching track T%d S%d s%d z%d\n", 483},
  {"FDCmatchIDmarker failed\n", 484},
  {"FDCmatchIDmarker succeeded: track %d, sector %d, side %d, size %d\n", 485},
  {"FDC read sector, T%d S%d s%d\n", 486},
  {"FDC write sector, T%d S%d s%d\n", 487},
  {"FDC write track, #%d\n", 488},
  {"FDC read track, #%d\n", 489},
  {"FDC read ID marker: track=%d sector=%d side=%d size=%d\n", 490},
  {"FDC interrupt\n", 491},
  {"FDC read status >%04X = >%02X\n", 492},
  {"FDC read track addr >%04X = >%02X\n", 493},
  {"FDC read sector addr >%04X = >%02X\n", 494},
  {"FDC read data (%d) >%02X (%d)\n", 495},
  {"FDC read write xxx >%04X = >%02X\n", 496},
  {"FDC write read xxx >%04X, >%02X\n", 497},
  {"FDC command >%02X\n", 498},
  {"unknown FDC command >%02X\n", 499},
  {"FDC write track addr >%04X, >%02X\n", 500},
  {"FDC write sector addr >%04X, >%02X\n", 501},
  {"FDC write data (%d,%d) >%02X\n", 502},
  {"Unexpected data write >%02X for command >%02X\n", 503},
  {"real disk DSR on\n", 504},
  {"DSR Read >4000 = >%02X\n", 505},
  {"real disk DSR off\n", 506},
  {"CRU Motor %s\n", 507},
  {"CRU hold %s\n", 508},
  {"CRU Heads %s\n", 509},
  {"CRU disk select, #%d\n", 510},
  {"opening (DSK.num=%d)\n", 511},
  {"closing\n", 512},
  {"CRU disk side #%d\n", 513},
  {"\
DOAD server:  DSK%d (%s) is inaccessible\n\
when emulated (FIAD) disk DSR is loaded\n", 514},
  {"Changing disk %d while it's being accessed!\n", 515},
  {"TI Disk DSR Options", 516},
  {"These commands control the TI 'real' disk-on-a-disk (DOAD) emulation", 517},
  {"Set directory list to search for DOAD disk images", 518},
  {"path", 519},
  {"list of directories separated by one of these characters: '", 520},
  {"DOAD image in drive 1", 521},
  {"name of DOAD image", 522},
  {"DOAD image in drive 2", 523},
  {"DOAD image in drive 3", 524},
  {"Name of DSR ROM image which fits in the CPU address space >4000...>5FFF", 525},
  {"setting up TI real-disk DSR ROM\n", 526},
  {"TI disk DSR ROM", 527},
  {"No keyboard driver loaded\n", 528},
  {"\
Binding %scommand to '%s':\n\
\t%s\n", 529},
  {"up ", 530},
  {"down ", 531},
  {"\
Unbinding old 'up' command:\n\
\t%s\n\
\n", 532},
  {"\
Unbinding old 'down' command:\n\
\t%s\n\
\n", 533},
  {"BindKey: key '%s' not defined\n", 534},
  {"<no keys to bind>\n", 535},
  {"<%s unavailable>\n", 536},
  {"<empty>", 537},
  {"<no keys bound>\n", 538},
  {"Map of keyboard CRU:\n", 539},
  {"Keyboard / Joystick Options", 540},
  {"\
These are generic commands for controlling the keyboard and joystick \
emulation", 541},
  {"\
Enable or disable ALPHA LOCK state (i.e., upon startup; CAPS performs this \
function at runtime)", 542},
  {"Bind a non-TI key to a command", 543},
  {"key", 544},
  {"\
symbolic name of key (see ListKeys); bare key name means 'perform command \
when key is pressed'; +key means 'perform command when key is pressed' and \
'perform command bound to -key when key is released'", 545},
  {"command", 546},
  {"text of command to execute", 547},
  {"List symbolic names of bindable keys", 548},
  {"List current key bindings", 549},
  {"Display map of current TI keys held down", 550},
  {"Reset keyboard (i.e. when a key seems stuck)", 551},
  {"\
Enable software keyboard mode; this mode remembers only the last key pressed \
and flushes the keyboard map at regular intervals; used with clients that do \
not reliably send key release events.  Default set by client.", 552},
  {"off|on", 553},
  {"\
off: assume key press and release events are reliable\n\
on: handle one key at a time, flush keymap KeyboardFlushRate times per \
second\n", 554},
  {"\
Control rate keyboard map is cleared when SoftKeyScanning mode is enabled \
and keyboard is idle", 555},
  {"hertz", 556},
  {"times per second to flush keyboard map\n", 557},
  {"Illegal special key value %d in %s, ignoring\n", 558},
  {"\
Activating binding for +'%s'\n\
\n\
\n", 559},
  {"\
Nothing bound to '+%s'\n\
\n", 560},
  {"\
Special key %d not supported\n\
\n", 561},
  {"\
Activating binding for -'%s'\n\
\n", 562},
  {"Resetting %d for key %d\n", 563},
  {"\
keyboard_setkey:  got a key that should be faked '%c' (%d)\n\
\n", 564},
  {"Clearing fake shifts\n", 565},
  {"\
keyboard_isset:  got a key that should be faked '%c' (%d)\n\
\n", 566},
  {"\
changing JOY_X (%d)\n\
\n", 567},
  {"\
changing JOY_Y (%d)\n\
\n", 568},
  {"\
changing JOY_B (%d)\n\
\n", 569},
  {"\
\n\
%s (a TI-99/4A Emulator) version %s\n\
%s comes with ABSOLUTELY NO WARRANTY; for details type 'license'\n\
Type 'exit' to continue emulating, 'quit' to quit %s\n\
\n", 570},
  {"Enter a command> ", 571},
  {"<EOF>\n", 572},
  {"inserting keyboard delay hack\n", 573},
  {"Calibrating processor... ", 574},
  {"\
%Ld bogocycles.\n\
\n", 575},
  {"Cannot set PC to %04X, ignoring\n", 576},
  {"Cannot set WP to %04X, ignoring\n", 577},
  {"Can't access memory type '%s'\n", 578},
  {"\
Mismatched on RLE compress:\n\
In : %s\n\
Out: %s\n\
Ver: %s\n", 579},
  {"end address (>%04X) less than start address (>%04X)", 580},
  {"end address (>%04X) equals start address (>%04X)", 581},
  {"Internal Emulator Commands", 582},
  {"These options affect the mechanics of 99/4A emulation", 583},
  {"\
Toggle real-time emulation mode (attempts to operate at the same speed of \
the original 9900)", 584},
  {"on:  execute at 9900 speed; off:  execute with DelayBetweenInstructions", 585},
  {"Sets a constant delay between instructions (when not in real-time mode)", 586},
  {"cycles", 587},
  {"number of cycles to count", 588},
  {"Resets the 99/4A via RESET", 589},
  {"Pauses emulation of the 99/4A", 590},
  {"Enable the debugger/tracer", 591},
  {"Allow interrupts to occur while debugging", 592},
  {"\
Check for locked-up 99/4A and enter interactive mode. The test is very \
simple and may not be true in all cases.", 593},
  {"Execute one instruction and stop", 594},
  {"Set HZ speed base clock (usually 3.0 MHz)", 595},
  {"number of times per second", 596},
  {"Memory / Debugging Commands", 597},
  {"\
These options allow you to change the running state of the virtual machine", 598},
  {"Set the program counter", 599},
  {"illegal addresses will be ignored", 600},
  {"Set the workspace pointer", 601},
  {"Set the status register", 602},
  {"Set the VDP address register", 603},
  {"Set a VDP register", 604},
  {"register", 605},
  {"register number, 0-7", 606},
  {"value", 607},
  {"value for register", 608},
  {"Set VDP read-ahead value", 609},
  {"byte", 610},
  {"next byte to read from VDP RAM", 611},
  {"Set VDP address", 612},
  {"flag", 613},
  {"value of flag, 0 for high, 1 for low", 614},
  {"Set the GROM address register", 615},
  {"Read contents of memory", 616},
  {"contents", 617},
  {"memory bytes formatted into a single word", 618},
  {"type", 619},
  {"memory type: C/V/G/S", 620},
  {"bytes", 621},
  {"number of bytes to read (1, 2, or 4)", 622},
  {"Write contents of memory", 623},
  {"\
memory type: C/V/G/S, plus R to force writing of ROM (only valid if memory \
is not mapped as zero)", 624},
  {"number of bytes to write (1, 2, or 4)", 625},
  {"data", 626},
  {"data to write, as a single integer", 627},
  {"Change contents of multiple consecutive bytes of RAM", 628},
  {"string", 629},
  {"hexadecimal string", 630},
  {"Write contents of memory to a file (no headers!)", 631},
  {"file to write", 632},
  {"start address", 633},
  {"end address", 634},
  {"Load contents of memory from a file (no headers!)", 635},
  {"file to read", 636},
  {"Set all RAM to a known pattern (0xAA55)", 637},
  {"on:  dump trace to stdout; off:  don't", 638},
  {"\
\n\
Invalid workspace pointer set (>%04X);\n\
emulated 99/4A is probably locked up.\n\
(If this is the first thing V9t9 is doing,\n\
perhaps your ROMs are missing or misconfigured?)\n\
\n\
Enter 'SanityCheckLockupState off' to disable this message.\n", 639},
  {"emulate_keyslow; slowing=%d, resume=%d\n", 640},
  {"got a keypress [%02X : %02X]\n", 641},
  {"slowing down...\n", 642},
  {"different key [%02X != %02X] : %02X\n", 643},
  {"GTK Options", 644},
  {"These commands control the GTK interface", 645},
  {"\
Set the number of times per second that the debugger refreshes in 'Run' mode", 646},
  {"rate", 647},
  {"update rate in hertz", 648},
  {"Set the font used for the 'Command Central' window", 649},
  {"font", 650},
  {"\
font string in X11 format, i.e., '-adobe-utopia-regular-r-normal-*-*-120-*-*-\
p-*-iso8859-1'", 651},
  {"\
\n\
Emulator is paused; press 'Resume' button to resume\n", 652},
  {"Executing %d cycles per second, %d instructions per second", 653},
  {"Displaying %d frames per second", 654},
  {"Unhandled event %d!", 655},
  {"Illegal workspace pointer set (>%04X)\n", 656},
  {"Invalid program counter set (>%04X), aborting\n", 657},
  {"*** BLWP'ing to same workspace, may be hosed\n", 658},
  {"unhandled extended opcode >%04X at >%04X [%d]\n", 659},
  {"\
set_area_handler:  attempt made to set a memory handler on an illegal \
boundary\n\
(0x%04X...0x%04X), the minimum granularity is %d bytes\n", 660},
  {"\
set_area_handler:  cannot have a handler define read_word without read_byte\n", 661},
  {"\
set_area_handler:  cannot have a handler define write_word without \
write_byte\n", 662},
  {"set_area_handler:  must have areamemory set\n", 663},
  {"set_area_handler:  domain out of range\n", 664},
  {"set_area_handler:  illegal address or size\n", 665},
  {"\
\n\
Memory map (%s):\n", 666},
  {"'%s': Addr: >%04X, Offs: >%04X, Size: >%04X (>%04X)\n", 667},
  {"\tFilename: '%s'\n", 668},
  {"\tFlags:", 669},
  {"invalid MEMENT_xxx: %d\n", 670},
  {"memory_remove_entry_from_list", 671},
  {"\
Splitting entry '%s' into >%04X (>%04X), >%04X (>%04X), and >%04X (>%04X)\n", 672},
  {"Shrinking entry '%s' to >%04X (>%04X)\n", 673},
  {"Overriding old entry '%s' at >%04X (>%04X)\n", 674},
  {"Saving memory image to '%s'\n", 675},
  {"Restoring memory image from '%s'\n", 676},
  {"Image '%s' ('%s') not found, resetting to zero\n", 677},
  {"Reading ROM image '%s' at %d to >%04X, size %d\n", 678},
  {"Zeroes for '%s' at >%04X, size %d\n", 679},
  {"Resetting memory area from >%04X to >%04X\n", 680},
  {"Can't locate '%s'\n", 681},
  {"Unknown memory type '%c' (at '%s')\n", 682},
  {"Unknown memory flag '%c' (at '%s')\n", 683},
  {"Illegal address (>%04x) for entry\n", 684},
  {"Address is impossible to use, minimum granularity is >%04x bytes\n", 685},
  {"\
Illegal size (%d) for entry, should have magnitude between 0 and >FFFF\n", 686},
  {"\
Size (>%04X) for entry plus starting address (>%04X) too large; truncating\n", 687},
  {"Illegal size for RAM entry, must be >= 0 (%d)\n", 688},
  {"Entry is impossible to allocate, minimum granularity is >%04X bytes\n", 689},
  {"Low expansion RAM", 690},
  {"Console RAM (256 bytes)", 691},
  {"Console RAM (1K)", 692},
  {"High expansion RAM", 693},
  {"Sound MMIO", 694},
  {"VDP read MMIO", 695},
  {"VDP write MMIO", 696},
  {"Speech read MMIO", 697},
  {"Speech write MMIO", 698},
  {"GROM read MMIO", 699},
  {"GROM/GRAM write MMIO", 700},
  {"Initializing memory...\n", 701},
  {"Not saved to configuration file\r", 702},
  {"Only saved to session files\r", 703},
  {"Only saved to config files\r", 704},
  {"Arguments%s:\t", 705},
  {" (optional)", 706},
  {"Returns first argument\r", 707},
  {"Returns:\r", 708},
  {"No command matches '%s'\n", 709},
  {"No commands defined\n", 710},
  {"Button mapped to missing option '%s'\n", 711},
  {"Text entry mapped to missing option '%s'\n", 712},
  {"Select ROM Filename", 713},
  {"Could not resolve filename '%s' (%s)\n", 714},
  {"Save Session File", 715},
  {"Load Session File", 716},
  {"Sessions", 717},
  {"Configurations", 718},
  {"Cannot get log_table from dialog\n", 719},
  {"unhandled instruction %s\n", 720},
  {"could not create %s in %s", 721},
  {"out of memory", 722},
  {"compiler failed to build segment\n", 723},
  {"compiler failed to open file '%s' (%s)\n", 724},
  {"compiler failed to write text(1) to file '%s' (%s)\n", 725},
  {"compiler failed to write text(2) to file '%s' (%s)\n", 726},
  {"compiler failed to write text(3) to file '%s' (%s)\n", 727},
  {"did not write source text", 728},
  {"could not execute 'make' (%s)\n", 729},
  {"error compiling code (see %s)\n", 730},
  {"could not locate '%s'\n", 731},
  {"Could not load code block '%s' (%s)\n", 732},
  {"Could not resolve symbol 'native' in '%s' (%s)\n", 733},
  {"flushing code block at >%04X due to workspace overlap\n", 734},
  {"flushing compile cache for %s(%04x) due to memory content change\n", 735},
  {"Compiler Options", 736},
  {"These are commands for controlling real-time compilation", 737},
  {"enable or disable real-time compilation of 9900 code", 738},
  {"Set compiler temporary directory", 739},
  {"directory", 740},
  {"temporary directory", 741},
  {"Couldn't find pixmap file: %s", 742},
  {"Triggering interrupt... %04X/%04X/%04X\n", 743},
  {"Altering 9901 bit... addr=%04X, data=%04X,mask=%04X\n", 744},
  {"before reset: int9901 = %04X, currentints = %04X\n", 745},
  {"after reset: int9901 = %04X, currentints = %04X\n", 746},
  {"audiogate.play=%d\n", 747},
  {"Error loading pixmap file: %s", 748},
  {"Out of memory for config file\n", 749},
  {"Unhandled type in dump_command (%d)\n", 750},
  {"Saving %s file to %s\n", 751},
  {"session", 752},
  {"config", 753},
  {"Cannot write to %s\n", 754},
  {"\
#\n\
#  v9t9 configuration file\n\
#\n", 755},
  {"\
Could not save config file to '%s' in:\n\
%s\n", 756},
  {"\
Could not find config file '%s' in:\n\
%s\n", 757},
  {"\
Could not save session to '%s' in:\n\
%s\n", 758},
  {"\
Could not find session file '%s' in:\n\
%s\n", 759},
  {"\
Unknown option '%s %s';\n\
expected one of %s \n", 760},
  {"Using GTK\n", 761},
  {"Using DrawDib\n", 762},
  {"Using DirectDraw\n", 763},
  {"Could not find a frontend\n", 764},
  {"timer init\n", 765},
  {"Could not get timer caps\n", 766},
  {"timerRes = %d\n", 767},
  {"timer install\n", 768},
  {"\
Could not set timer to %d ms\n\
\n", 769},
  {"Could not create timer event\n", 770},
  {"timer uninstall\n", 771},
  {"Could not create timer\n", 772},
  {"Could not set timer to 10 ms", 773},
  {"\
Entering interactive mode\n\
\n", 774},
  {"\
FAILED: could not open stdin/stdout\n\
\n", 775},
  {"could not open log.win.txt\n", 776},
  {"Could not get stdout for console\n", 777},
  {"V9t9 Log", 778},
  {"Execution is %s\n", 779},
  {"resumed", 780},
  {"\
win_command: %d\n\
\n", 781},
  {"Directories", 782},
  {"Files", 783},
  {"OK", 784},
  {"Cancel", 785},
  {"Directory unreadable: %s", 786},
  {"Create Dir", 787},
  {"Delete File", 788},
  {"Rename File", 789},
  {"Error", 790},
  {"Close", 791},
  {"Create Directory", 792},
  {"Directory name:", 793},
  {"Create", 794},
  {"Delete", 795},
  {"Rename", 796},
  {"Selection: ", 797},
  {"GRAMKRACKER base filename should have at most one '%%d' (got '%s')\n", 798},
  {"GRAMKRACKER base filename cannot have both a ',' and '%' (got '%s')\n", 799},
  {"Could not find GRAM Kracker segment '%s' (in '%s')\n", 800},
  {"\
Could not find expected remaining GRAM Kracker segments\n\
numbered starting at %d", 801},
  {"Could not find first segment of GRAM Kracker file with base '%s'\n", 802},
  {"List of installed modules:", 803},
  {"Tag: '%s', Name: '%s'\n", 804},
  {"\tCommands:  '%s'\n", 805},
  {"Loading module '%s'\n", 806},
  {"No module matches '%s'\n", 807},
  {"memory bank must be 0 or 1 (got %d)\n", 808},
  {"Memory Map / ROM / RAM / Module Options", 809},
  {"\
These are commands for dealing with the layout of memory in the virtual 99/4A", 810},
  {"Set secondary directory list to search for module ROM images", 811},
  {"Set secondary directory list to search for console ROM and GROM images", 812},
  {"Set secondary directory list to search for nonvolatile RAM images", 813},
  {"Set initial directory list to search for module ROM images", 814},
  {"Set initial directory list to search for console ROM and GROM images", 815},
  {"Set initial directory list to search for nonvolatile RAM images", 816},
  {"Specify existence of a memory area", 817},
  {"flags", 818},
  {"\
string of characters defining memory characteristics:\n\
first, 'R' for ROM, 'W' for RAM, and 'S' for stored RAM;\n\
then, 'M' for a module, or nothing;\n\
then, '1' or '2' for banks of a banked module, or nothing;\n\
then, one of 'C'onsole, 'G'raphics, 'V'ideo, 'S'peech", 819},
  {"starting address of image", 820},
  {"size", 821},
  {"\
size of ROM in bytes; except for 0, which indicates an unknown size, and a \
negative number (enclose in parentheses!), which indicates the magnitude of \
the maximum size allowed ", 822},
  {"\
name of binary image to load and/or store, searched in the ROMSPath or \
ModulesPath; if blank, memory is read as zeroes", 823},
  {"offset", 824},
  {"byte offset of image, if stored in larger file", 825},
  {"name", 826},
  {"text name of memory area", 827},
  {"Setup defaults for a 99/4A memory map", 828},
  {"Use 32K expansion memory (may be overridden by a DefineRAM command)", 829},
  {"toggle", 830},
  {"\
Set up >8000->82FF range as real RAM (like in the Geneve) instead of \
mirroring >8300->83FF (the default)", 831},
  {"Name of console ROM which starts at address >0000", 832},
  {"Name of console GROM which starts at address G>0000", 833},
  {"Name of module GROM which starts at address G>6000", 834},
  {"Name of module ROM (non-banked) which starts at CPU address >6000", 835},
  {"Name of module ROM (first bank) which starts at CPU address >6000", 836},
  {"Name of module ROM (second bank) which starts at CPU address >6000", 837},
  {"Load all memory images (ROMs and RAMs) into the emulator", 838},
  {"Load the volatile memory images (RAMs) into the emulator", 839},
  {"Save the volatile memory images (RAMs) to disk", 840},
  {"List memory map", 841},
  {"Define or redefine a standard module/cartridge in the database", 842},
  {"tag", 843},
  {"short tag for easy reference", 844},
  {"full name of module", 845},
  {"base", 846},
  {"base of module file name", 847},
  {"GROM=1|ROM=2|BANKED=4|MINIMEM=8|GRAMKRACKER=16", 848},
  {"sections present (sum of one or more of GROM, ROM, BANKED, MINIMEM)", 849},
  {"\
Define or redefine a module/cartridge in the database, giving commands to \
define its memory configuration", 850},
  {"commands", 851},
  {"\
commands used to define module memory map, e.g., 'DefineMemory \"RWMC\" \
0x6000 0x2000 \"module_rom.bin\" 0x0 \"Module ROM file\"; DefineMemory \"RMG\
\" 0x6000 0x6000 \"module_grom.bin\" 0x0 \"Module GRAM file\"'", 852},
  {"List modules in database", 853},
  {"\
Initialize current module list to empty (use 'ReadModuleDatabase <file>' or \
LoadConfigFile <file>' to add entries)", 854},
  {"\
Unload currently loaded module(s); you may want to 'ResetComputer' next!", 855},
  {"Load a module by tag or name", 856},
  {"tag|name", 857},
  {"tag or title substring", 858},
  {"Replace current module but do not reset computer", 859},
  {"Change active ROM bank of module (only applies to banked modules)", 860},
  {"bank", 861},
  {"0 or 1", 862},
  {"crudevicedump:", 863},
  {"\tREAD:\n", 864},
  {"\t\tdevice = >%04X (%p)\n", 865},
  {"\tWRITE:", 866},
  {"cruadddevice:  address 0x%x is invalid\n", 867},
  {"cruadddevice:  only single-bit ranges supported (0x%04X, %d)\n", 868},
  {"cruadddevice:  invalid 'rw' flag (%d) passed\n", 869},
  {"cruadddevice:  overlapping I/O (0x%x)\n", 870},
  {"crudeldevice:  address 0x%x is invalid\n", 871},
  {"crudeldevice:  only single-bit ranges supported (0x%04X, %d)\n", 872},
  {"crudeldevice:  invalid 'rw' flag (%d) passed\n", 873},
  {"crudeldevice:  device not found (0x%x)\n", 874},
  {"CRU write: >%04X[%d], %04X\n", 875},
  {"cruwrite:  skipping bits, range is now %04X[%d]\n", 876},
  {"cruwrite:  handling %04X[%d] with %04X\n", 877},
  {"CRU read: >%04X[%d] = \n", 878},
  {"cruread:  skipping bits, range is now %04X[%d]\n", 879},
  {"cruread:  handling %04X[%d] with %04X\n", 880},
  {"\
mix_init: swapendian=%d\n\
\n", 881},
  {"accessing outside sampleblock (%d, %d)\n", 882},
  {"samples:\t", 883},
  {"[start=%d, size=%d] ", 884},
  {"mix_handle_voice: channel %d, hertz = 0x%x, volume = %d\n", 885},
  {"ignoring tone at %d Hz\n", 886},
  {"mix_handle_noise: channel %d, hertz = 0x%x, volume = %d, iswhite = %d\n", 887},
  {"mix_handle_data: using %d bytes of %d Hz data on channel %d\n", 888},
  {"writing %d bytes of %d as audio gate\n", 889},
  {"\
\n\
V9t9: TI Emulator! v7.0\n\
\n\
v9t9 {options} {file|commands}...\n\
\n\
-h:       display help\n\
-c:       load alternate config file (default 'v9t9.cnf')\n\
-m:       load alternate module database (default 'modules.inf' if\n\
          'ReadModuleDatabase' command not present in config)\n\
-r:       reboot instead of loading previous 'session.cnf'\n\
-d <dir>: set v9t9 data directory to <dir>\n\
          (default: '%s',\n\
          '%s', or '.')\n\
file |    try to load session file; if not found, execute as\n\
commands: commands instead\n\
\n", 890},
  {"\
\n\
V9t9: TI Emulator! v7.0\n\
\n\
v9t9 {options} {file|commands}...\n\
\n\
-h:       display help\n\
-c:       load alternate config file (default '~/.v9t9/v9t9.cnf')\n\
-r:       reboot instead of loading previous 'session.cnf'\n\
-d <dir>: set v9t9 data directory to <dir> (default '~/.v9t9')\n\
file |    try to load session file; if not found, execute as\n\
commands: commands instead\n\
\n", 891},
  {"could not locate home directory, using current directory\n", 892},
  {"directory '%s' not found\n", 893},
  {"config file '%s' not found\n", 894},
  {"modules db '%s' not found\n", 895},
  {"session file '%s' not found\n", 896},
  {"\
executing commands may have no apparent effect when '-r' is used;\n\
specify '-e <cmds>' before '-r' if necessary\n", 897},
  {"config file 'v9t9.cnf' not found\n", 898},
  {"default config file 'v9t9.cnf' not found\n", 899},
  {"default modules db 'modules.inf' not found\n", 900},
  {"could not load session file '%s'\n", 901},
  {"could not execute demo '%s'\n", 902},
  {"could not execute commands '%s'\n", 903},
  {"No 'session.cnf' found; restarting\n", 904},
  {"Major Emulator Commands", 905},
  {"These are general commands to control the emulator", 906},
  {"Display command help", 907},
  {"option", 908},
  {"option (or prefix) to get help for", 909},
  {"Display GPL license and terms of use", 910},
  {"Control whether emulator waits for user commands", 911},
  {"\
if 'on', emulation will halt; if 'off', emulation continues at end of \
command list", 912},
  {"Exit from interactive mode (same as 'Interactive=off')", 913},
  {"Exit V9t9 without saving session", 914},
  {"Exit V9t9 and save session", 915},
  {"Set V9t9 installation directory", 916},
  {"directory root where V9t9 was installed (i.e., /usr/share/v9t9)", 917},
  {"Set fallback directory list for loading and storing data files", 918},
  {"Set directory list for searching and saving configuration files", 919},
  {"Set directory list for searching and saving session files", 920},
  {"Save current configuration settings to 'file'", 921},
  {"name of config file", 922},
  {"\
Load configuration settings from 'file', or merge module list from 'file'", 923},
  {"name of config file or modules.inf file", 924},
  {"Save current configuration settings and machine state to 'file'", 925},
  {"Load configuration settings and machine state from 'file'", 926},
  {"Take a screenshot and save to 'file' or an autogenerated name", 927},
  {"\
name of file to write, or \"\" to use an automatic name in the current \
directory", 928},
  {"VDP memory", 929},
  {"vdp_update_params:  blank screen\n", 930},
  {"vdp_update_params:  graphics mode\n", 931},
  {"vdp_update_params:  text mode\n", 932},
  {"vdp_update_params:  bitmap mode\n", 933},
  {"vdp_update_params:  multi mode\n", 934},
  {"\
Unknown graphics mode %d set\n\
\n", 935},
  {"Undefined VDP register %d\n", 936},
  {"char %d changed due to patt %d\n", 937},
  {"redrawing char %d\n", 938},
  {"Video Options", 939},
  {"These are generic commands for controlling video emulation", 940},
  {"Control whether the screen is displayed", 941},
  {"toggle video on or off", 942},
  {"Control how often the screen is updated", 943},
  {"Control how often the VDP interrupts the CPU", 944},
  {"Control whether sprites are displayed", 945},
  {"toggle sprites on or off", 946},
  {"Obey five-sprites-on-a-line limit of TMS9918A", 947},
  {"\
on: fifth sprite on a line not drawn (default); off: all sprites always drawn", 948},
  {"Could not open '%s' for writing\n", 949},
  {"Could not initialize PNG subsystem\n", 950},
  {"Failed to write PNG file '%s'\n", 951},
  {"Writing to '%s'\n", 952},
  {"Could not make a filename for screen shot\n", 953},
  {"Could not create '%s' for screen shot\n", 954},
  {"No graphics file formats supported!\n", 955},
  {"xmalloc:  failed in allocation of %d bytes\n", 956},
  {"\
xcalloc:  failed in allocation of %d bytes\n\
\n", 957},
  {"\
xrealloc:  failed in reallocation to %d bytes\n\
\n", 958},
  {"\
xstrdup:  failed to copy string\n\
\n", 959},
  {"\
xintdup:  failed to copy int\n\
\n", 960},
  {"Equation: %s\n", 961},
  {"ebf=%d, pbf=%d, env=%d, pnv=%d\n", 962},
  {"Unknown subsystem '%s'\n", 963},
  {"Supported logging subsystems:", 964},
  {"\t%20s\t(level=%d)", 965},
  {"Logging Commands", 966},
  {"These options control sources and verbosity of logging", 967},
  {"Toggle logging for given subsystem", 968},
  {"system", 969},
  {"one of the subsystems from ListLogSystems", 970},
  {"log level", 971},
  {"\
level of verbosity (0=off...9=max); a negative value sends output only to \
file, else output is copied to console or log window", 972},
  {"List targets for logging", 973},
  {"Change logging verbosity for log file", 974},
  {"delta", 975},
  {"delta>0 increases verbosity, delta<0 decreases verbosity", 976},
  {"\
Change logging verbosity for messages echoed to console; note:  LogVerbosity \
is treated as being at least ConsoleLogVerbosity, so messages will always be \
logged to disk", 977},
  {"\
\n\
OS error:\t", 978},
  {"%s (error %d)\n", 979},
  {"Disk %d %s\n", 980},
  {"on", 981},
  {"off", 982},
  {"RS232/%d %s\n", 983},
  {"PIO %s\n", 984},
  {"assertion failed:  %s:%d: %s\n", 985},
  {"ResetComputer\n", 986},
  {"void", 987},
  {"symbol", 988},
  {"number", 989},
  {"enumeration", 990},
  {"filepath", 991},
  {"boolean", 992},
  {"negate", 993},
  {"()", 994},
  {"get_indexed_string: '%s' #%d --> '%s'\n", 995},
  {"%s:  ambiguous identifier (collides with '%s')\n", 996},
  {"for '%s', matched '%s' (%d)\n", 997},
  {"<unnamed>", 998},
  {"a number", 999},
  {"a string", 1000},
  {"a filespec", 1001},
  {"a pathspec", 1002},
  {"a filename", 1003},
  {"one of the items in the list", 1004},
  {"Unhandled size in command_arg_read_num (%d)\n", 1005},
  {"Unhandled size in command_arg_set_num (%d)\n", 1006},
  {"argument '%s': cannot set to '%s' (%s)\n", 1007},
  {"'%s' does not match an enumeration in '%s'\n", 1008},
  {"Unhandled ca_XXXX (%s)\n", 1009},
  {"%s:  unexpected additional %s argument #%d\n", 1010},
  {"%s:  type mismatch in argument '%s' (expected %s)\n", 1011},
  {"command_set_args:  cannot handle %s\n", 1012},
  {"%s:  expected additional parameters\n", 1013},
  {"invalid expr type %d\n", 1014},
  {"invalid expr rtype %d\n", 1015},
  {"cannot combine lists with '%s'\n", 1016},
  {"invalid binary expr type '%s'\n", 1017},
  {"invalid use of 'void' expression\n", 1018},
  {"type mismatch in '%s' %s '%s'\n", 1019},
  {"cannot modify list with '%s'\n", 1020},
  {"invalid unary expr type %s\n", 1021},
  {"unhandled ca_XXX (%s)", 1022},
  {"<void>", 1023},
  {"command_expr_type_stringify: unhandled type '%s'", 1024},
  {"Division by zero\n", 1025},
  {"unhandled ce_XXX: '%s'\n", 1026},
  {"unexpected arguments to '%s' (%s, %s)\n", 1027},
  {"unexpected arguments to '%s' (%s)\n", 1028},
  {"command_expr_evaluate: unhandled type '%s'\n", 1029},
  {"expected sum of enumeration values from '%s'\n", 1030},
  {"command_exprlist_evaluate: forcing to enum argument\n", 1031},
  {"arg '%s' type '%s', expr type '%s'\n", 1032},
  {"<expression>", 1033},
  {"log", 1034},
  {"assert", 1035},
  {"unknown identifier '%s'\n", 1036},
  {"unnesting past NULL command_exec_context\n", 1037},
  {"assertion '%s' failed\n", 1038},
  {"unhandled statement type '%s'\n", 1039},
  {"V9t9 Options", 1040},
  {"\
This is the complete list of options and commands you may specify in a \
configuration file or command prompt.", 1041},
  {"Could not create mutex for command parser", 1042},
  {"fiad_filename_ti2dos:  incoming = '%.*s', outgoing = '%s'\n", 1043},
  {"fiad_filename_ti2host:  incoming = '%.*s', outgoing = '%s'\n", 1044},
  {"FIAD server:  renaming old-style file '%s' to '%s'\n", 1045},
  {"FIAD server:  could not rename file (%s)\n", 1046},
  {"fiad_filename_host2ti:  incoming: '%s', outgoing: '%.10s'\n", 1047},
  {"FIAD server:  invalid flags %02x for file '%s'\n", 1048},
  {"\
FIAD server:  invalid number of sectors %d for data size %d in file '%s'\n", 1049},
  {"\
FIAD server:  record length %d / records per sector %d invalid\n\
for FIXED file '%s'\n", 1050},
  {"\
FIAD server:  record length %d / records per sector %d invalid\n\
for VARIABLE file '%s'\n", 1051},
  {"\
FIAD server:  record length %d / records per sector %d invalid\n\
for PROGRAM file '%s'\n", 1052},
  {"setup FDR name as '%.10s'\n", 1053},
  {"%s: could not read FDR\n", 1054},
  {"%s: FDR is short\n", 1055},
  {"\
TIFILES read> secsused=%04X, flags=%x, recspersec=%x, byteoffs=%x, reclen=%\
d, numrecs=%04X\n", 1056},
  {"\
V9t9 read> secsused=%04X, flags=%x, recspersec=%x, byteoffs=%x, reclen=%d, \
numrecs=%04X\n", 1057},
  {"Treating '%s' as text\n", 1058},
  {"File '%s' does not appear to be a V9t9 file\n", 1059},
  {"%s: Trying to write FDR on a closed or read-only file\n", 1060},
  {"%s: could not write FDR\n", 1061},
  {"%s: wrote short FDR\n", 1062},
  {"FIAD server: can't read FDR from file '%s'\n", 1063},
  {"FIAD server:  FDR is short in file '%s'\n", 1064},
  {"FIAD server:  repaired fields of FDR in '%s'\n", 1065},
  {"fiad_tifile_open_file: '%s', create: %d, always: %d, readonly: %d\n", 1066},
  {"created FIAD file '%s'\n", 1067},
  {"Failed to verify, creating new file\n", 1068},
  {"Truncating file\n", 1069},
  {"fiad_tifile_rewrite_fdr: File is open!\n", 1070},
  {"%s: changing file format to %s\n", 1071},
  {"%s: rewriting damaged FDR\n", 1072},
  {"\
FIAD ERROR:  file appears corrupt [curoffs=%d, len=%d]\n\
\n\
\n", 1073},
  {"\
fixed read, wanted %d, max is %d\n\
\n", 1074},
  {"fixed write, at %d, cur is %d\n", 1075},
  {"\
file has >%04X or %d sectors\n\
\n", 1076},
  {"going to read at most %d bytes from file with size %d\n", 1077},
  {"\
trying to write %d bytes to file\n\
\n", 1078},
  {"reading dir\n", 1079},
  {"Skipping '%s' which doesn't appear to be a V9t9 file\n", 1080},
  {"\
got file '%s'\n\
\n", 1081},
  {"Invalid catalog sort '%d'\n", 1082},
  {"V9t9", 1083},
  {"Quit V9t9", 1084},
  {"Save current session before quitting?\n", 1085},
  {"_Yes, Save", 1086},
  {"_No, Don't Save", 1087},
  {"_Don't Quit", 1088},
  {"Select Font", 1089},
  {"Disks", 1090},
  {"DSK_1", 1091},
  {"DSK_2", 1092},
  {"DSK_3", 1093},
  {"DSK_4", 1094},
  {"DSK_5", 1095},
  {"Choose...", 1096},
  {"DSKx Mappings", 1097},
  {"_Convert file headers to:", 1098},
  {"_V9t9", 1099},
  {"_TIFILES", 1100},
  {"Treat _unknown files as DIS/VAR 80", 1101},
  {"Allow \"DSKx.\" catalogs _longer than 127 filenames", 1102},
  {"_Repair damaged V9t9 files", 1103},
  {"_Fixup filenames for files created with V9t9 for DOS", 1104},
  {"_Generate filenames compatible with V9t9 for DOS", 1105},
  {"DSR ROM Selection", 1106},
  {"_Lone", 1107},
  {"_Shared", 1108},
  {"File Directory Options", 1109},
  {"S_hared", 1110},
  {"Disk Image Options", 1111},
  {"Use file directories (FIAD)", 1112},
  {"Use disk images (DOAD)", 1113},
  {"Modules", 1114},
  {"Name", 1115},
  {"Tag", 1116},
  {"Commands", 1117},
  {"Show _setup commands", 1118},
  {"_Reset computer after load", 1119},
  {"_Unload", 1120},
  {"Pull out the module while V9t9 is running", 1121},
  {"_Load", 1122},
  {"Insert module", 1123},
  {"Re_fresh", 1124},
  {"Reload module database from \"modules.inf\"", 1125},
  {"V9t9 Debugger", 1126},
  {"Registers", 1127},
  {"WP", 1128},
  {"PC", 1129},
  {"Status", 1130},
  {"Instructions", 1131},
  {"CPU Memory 1", 1132},
  {"CPU Memory 2", 1133},
  {"VDP Memory", 1134},
  {"GROM/GRAM Memory", 1135},
  {"Speech Memory", 1136},
  {"_Run", 1137},
  {"Execute emulator with minimal debugger refresh", 1138},
  {"_Step", 1139},
  {"Step one instruction (even into calls) and break", 1140},
  {"_After", 1141},
  {"\
Execute until the PC reaches the next instruction (ignore conditional jumps)", 1142},
  {"_Break", 1143},
  {"Break execution", 1144},
  {"_Walk", 1145},
  {"Execute emulator with maximum debugger refresh", 1146},
  {"_Next", 1147},
  {"Execute until the PC reaches the next instruction (skip over calls)", 1148},
  {"Updates per second", 1149},
  {"Number of times debugger refreshes in \"Run\" mode", 1150},
  {"Memory Configuration", 1151},
  {"Console _ROM", 1152},
  {"Console _GROM", 1153},
  {"Use 32K _extended memory", 1154},
  {"Enable Gene_ve-style RAM in >8000->82FF range", 1155},
  {"Load custom module ROMs", 1156},
  {"_Module ROM", 1157},
  {"M_odule GROM", 1158},
  {"Module ROM (bank _1)", 1159},
  {"Module ROM (bank _2)", 1160},
  {"Resume", 1161},
  {"Continue emulation", 1162},
  {"Boot and Run", 1163},
  {"Close window and reset computer", 1164},
  {"Close window and continue emulation", 1165},
  {"Advanced options", 1166},
  {"Explore memory map", 1167},
  {"Unload module", 1168},
  {"Unload all ROMs and RAMs associated with a module", 1169},
  {"Save volatile RAM", 1170},
  {"These RAMs are saved automatically at certain points", 1171},
  {"Load volatile RAM", 1172},
  {"These RAMs are loaded automatically at certain points", 1173},
  {"Default memory map", 1174},
  {"\
Sets up RAM and memory-mapped areas to standard 99/4A settings in case there \
was a mishap with DefineMemory", 1175},
  {"Basic Options", 1176},
  {"Enable _sound", 1177},
  {"Enable s_peech", 1178},
  {"_Real-time emulation", 1179},
  {"_9900 Clock Speed", 1180},
  {"\
This affects the maximum execution speed when real-time emulation is enavbled", 1181},
  {"Default", 1182},
  {"Instruction _delay", 1183},
  {"This value is highly CPU-dependent", 1184},
  {"_Video refresh rate", 1185},
  {"\
This controls how often the changed parts of the 99/4A screen are redrawn", 1186},
  {"VDP _interrupt rate", 1187},
  {"This affects sprite motion and timing", 1188},
  {"Logging Configuration", 1189},
  {"Reset All", 1190},
  {"Fatal error", 1191},
  {"Memory Map", 1192},
  {"Console / CPU", 1193},
  {"GROM/GRAM", 1194},
  {"VDP", 1195},
  {"Speech", 1196},
  {"Refresh", 1197},
  {"Command Central", 1198},
  {"_Options", 1199},
  {"_Flush Log", 1200},
  {"_Select Font...", 1201},
  {"Welcome to V9t9!", 1202},
  {"Reboot", 1203},
  {"Reset emulated 99/4A", 1204},
  {"Pause", 1205},
  {"Pause execution of V9t9", 1206},
  {"Save...", 1207},
  {"Save machine state", 1208},
  {"Load...", 1209},
  {"Load machine state", 1210},
  {"Options...", 1211},
  {"Set basic configuration options", 1212},
  {"Debugger...", 1213},
  {"Control emulated 99/4A and trace execution", 1214},
  {"Modules...", 1215},
  {"Load or unload modules", 1216},
  {"Disks...", 1217},
  {"Assign drives to local directories or files", 1218},
  {"Memory...", 1219},
  {"Assign files to ROM or RAM segments of the memory map", 1220},
  {"Quit", 1221},
  {"Logging...", 1222},
  {"Modify log levels for debugging", 1223},
  {"SIGSEGV caught.\n", 1224},
  {"Can't un-set root privileges!\n", 1225},
  {"\
Unknown option '%s %s';\n\
expected one of %s\n", 1226},
  {"X11 not detected, using SVGAlib\n", 1227},
  {"X11 not detected, cannot use specified frontend\n", 1228},
  {"Using QT/Embedded\n", 1229},
  {"Using Xlib\n", 1230},
  {"Using SVGAlib\n", 1231},
  {"Could not use specified frontend\n", 1232},
  {"Entering interactive mode\n", 1233},
  {"FAILED: could not open terminal\n", 1234},
  {"Could not create log file\n", 1235},
  {"Could not create user log file\n", 1236},
  {"Done with speech phrase\n", 1237},
  {"Speech reset\n", 1238},
  {"\
Speech read: %02X\n\
\n", 1239},
  {"Speech addr = %04X\n", 1240},
  {"Speaking phrase at %04X\n", 1241},
  {"Speaking external data\n", 1242},
  {"\
Cmd=%02X  Status: %02X\n\
\n", 1243},
  {"FIFO write: %02X  len=%d\n", 1244},
  {"FIFO read: %02X  len=%d\n", 1245},
  {"Speech timed out\n", 1246},
  {"Speech Interrupt\n", 1247},
  {"Out of speech interrupt\n", 1248},
  {"Speech ROM", 1249},
  {"\
Sound module cannot play speech, speech disabled.\n\
\n", 1250},
  {"\
Setting up LPC speech...\n\
\n", 1251},
  {"Speech Options", 1252},
  {"These are commands for controlling speech synthesis", 1253},
  {"Control whether speech is played", 1254},
  {"toggle speech on or off", 1255},
  {"Name of speech ROM", 1256},
  {"Set sample rate for speech", 1257},
  {"normal value is 8000", 1258},
  {"Set sample length for a unit of speech", 1259},
  {"length", 1260},
  {"in bytes, normal value is 200", 1261},
  {"no usable memory at that address", 1262},
  {"\
setting multiple memory breakpoints in the same 1k area; unsetting any \
breakpoint in this area turns them all off", 1263},
  {"Active breakpoints:\n", 1264},
  {"\t<none>\n", 1265},
  {"Debugger Options", 1266},
  {"These commands control the debugger", 1267},
  {"Add a breakpoint at the given PC", 1268},
  {"PC address at which to break", 1269},
  {"Remove breakpoint at the given PC", 1270},
  {"PC address of breakpoint", 1271},
  {"\
Add temporary breakpoint at the given PC, which will be removed upon being \
caught", 1272},
  {"List active breakpoints", 1273},
  {"Add a breakpoint on memory access", 1274},
  {"address at which to break", 1275},
  {"access", 1276},
  {"access type: R/W/RW", 1277},
  {"Remove memory breakpoint at the given address", 1278},
  {"\
voice_cache_values: lo=>%02x, hi=>%02x, period=>%04x, hertz=%d, volume=%d\n", 1279},
  {"\
Cassette %d is %p (%s)\n\
\n", 1280},
  {"Invalid sound channel specified (%d)\n", 1281},
  {"Sound Options", 1282},
  {"These are generic commands for controlling sound emulation", 1283},
  {"\
Control whether music/noise sound is played.\n\
(Note: to turn off all sound, disable the sound module or use \"EnableSound \
off\".)", 1284},
  {"toggle sound on or off", 1285},
  {"Control whether any sound is emitted.", 1286},
  {"\
Set playback rate for digitized sound; interpretation is dependent on sound \
module in effect", 1287},
  {"set rate for playback", 1288},
  {"\
Set word size for digitized sound; interpretation is dependent on sound \
module in effect", 1289},
  {"set word size for playback", 1290},
  {"channel", 1291},
  {"channel number, 0-3", 1292},
  {"period", 1293},
  {"period of channel", 1294},
  {"volume", 1295},
  {"volume 0-15, 15=off", 1296},
  {"type of noise, or 0 for tone", 1297},
  {"Could not add %d bytes to demo (%s)\n", 1298},
  {"missing bytes on read (%d of %d, %s)\n", 1299},
  {"Invalid use of demo handle\n", 1300},
  {"buffer_poke:  overrun (%d+%d > %d)\n", 1301},
  {"Illegal buffer length %d (max = %d), pos = %d\n", 1302},
  {"Demo file is truncated (expected %d bytes at %d, got %d)\n", 1303},
  {"Setting up demo (%s)\n", 1304},
  {"Could not create demo file '%s' (%s)\n", 1305},
  {"Could not allocate memory for demo (%s)\n", 1306},
  {"Demo file header invalid (got %02x%02x%02x%02x, expected '%.*s''\n", 1307},
  {"Initiating demo (%s)\n", 1308},
  {"Could not load demo file %s (%s)\n", 1309},
  {"Initiating demo (%s / %s)\n", 1310},
  {"Could not open demo reader %s (%s)\n", 1311},
  {"Could not open demo writer %s (%s)\n", 1312},
  {"Initiating demo client on port %d\n", 1313},
  {"error creating listening socket (%s)\n", 1314},
  {"error calling connect() (%s)\n", 1315},
  {"Closing demo\n", 1316},
  {"Closing demo (%s)\n", 1317},
  {"Could not write demo file '%s' (%s)\n", 1318},
  {"Demo playback stopped.\n", 1319},
  {"Tick\n", 1320},
  {"Video >%04X, PC=>%04X ", 1321},
  {"Sound >%02X\n", 1322},
  {"Speech %d", 1323},
  {"Unknown event type passed to demo_event (%d)\n", 1324},
  {".", 1325},
  {"tick\n", 1326},
  {"Video %d\n", 1327},
  {"(video >%04x, %d bytes)\n", 1328},
  {"(video reg >%04x)\n", 1329},
  {"Sound %d\n", 1330},
  {"(sound %02x)\n", 1331},
  {"Speech %d\n", 1332},
  {"(speech %02x)\n", 1333},
  {"(type %d)\n", 1334},
  {"Demo appears to be corrupt at %d\n", 1335},
  {"Ending currently recording demo.\n", 1336},
  {"Stopping currently playing demo.\n", 1337},
  {"Invalid demo filename '%s' (%s)\n", 1338},
  {"Can't load demo '%s' (%s)\n", 1339},
  {"Can't load demo reader '%s' (%s)\n", 1340},
  {"Can't load demo writer '%s' (%s)\n", 1341},
  {"Demo Options", 1342},
  {"\
These commands control recording and playback of V9t9 demos, which do not \
require ROMs to view.", 1343},
  {"\
Set directory list to search for demo files; first entry of the list is used \
to save demos", 1344},
  {"Start recording a new demo", 1345},
  {"demo file to create", 1346},
  {"Start playing an existing demo", 1347},
  {"demo file to play", 1348},
  {"Start listening for demo data on fifos", 1349},
  {"demo read file", 1350},
  {"demo write file", 1351},
  {"Start listening for demo data on port", 1352},
  {"port to listen on", 1353},
  {"Pause recording or playback of demo", 1354},
  {"off: continues, on: pauses", 1355},
  {"Stop recording or playback of demo", 1356},
  {"NULL argument passed to data_find_file()", 1357},
  {"NULL argument passed to data_create_file()", 1358},
  {"\
Cannot find '%s' in path:\n\
'%s'\n", 1359},
  {"Loading %s image %s... ", 1360},
  {"%s too long, only %d bytes of %d read... ", 1361},
  {"could not read\n", 1362},
  {"swapping bytes... ", 1363},
  {"done\n", 1364},
  {"Couldn't create %s image %s anywhere in path: %s\n", 1365},
  {"\
Couldn't create %s image '%s' anywhere in path:\n\
'%s'\n", 1366},
  {"Writing %s image %s... ", 1367},
  {"swapping bytes to save... ", 1368},
  {"swapping bytes back... ", 1369},
  {"could not write\n", 1370},
  {"GRAM Kracker segment '%s' is not a PROGRAM file (it's %s)\n", 1371},
  {"\
GRAM Kracker segment '%s' is too long\n\
to be a segment (%d bytes > 8192+6 bytes)\n", 1372},
  {"\
Could not read signature for GRAM Kracker segment in V9t9 file '%s' (%s)\n", 1373},
  {"\
Could not read signature for GRAM Kracker segment in binary file '%s' (%s)\n", 1374},
  {"GRAM Kracker segment '%s' is a 'UTIL' segment (not supported)\n", 1375},
  {"GRAM Kracker segment '%s' is not a ROM file (got >%02X)\n", 1376},
  {"\
Can't get setuid root privileges!\n\
As root, execute 'chown root:root v9t9; chmod +s v9t9'\n\
to use the SVGAlib interface.\n\
\n", 1377},
  {"AddModule:  too many modules defined", 1378},
  {"AddModule:  module has no name\n", 1379},
  {"\
AddModule:  module has wrong module version (%d != %d)\n\
\n", 1380},
  {"AddModule: module has no specific module pointer\n", 1381},
  {"AddModule: CPU module '%s' has wrong version (%d)\n", 1382},
  {"AddModule: CPU module '%s' has NULL callback(s)\n", 1383},
  {"AddModule: video module '%s' has wrong version (%d)\n", 1384},
  {"AddModule: Video module has NULL callback(s)\n", 1385},
  {"AddModule: sound module has wrong version (%d)\n", 1386},
  {"\
AddModule: invalid sound module (has no callbacks and is not exclusive), \
ignoring\n", 1387},
  {"AddModule: keyboard module has wrong version (%d)\n", 1388},
  {"AddModule: Keyboard module has NULL callback(s)\n", 1389},
  {"AddModule: DSR module has wrong version (%d)\n", 1390},
  {"AddModule: DSR module has NULL callback(s)\n", 1391},
  {"AddModule:  module has unknown type (%d)\n", 1392},
  {"AddModule:  callback(s) missing in '%s'\n", 1393},
  {"CollectModules:  Could not find a %s module\n", 1394},
  {"SelectModules: unavailable, skipping\n", 1395},
  {"SelectModules: is unselected, skipping\n", 1396},
  {"SelectModules: not using since non-exclusive module already in use\n", 1397},
  {"\
SelectModules: not using since it doesn't satisfy missing callbacks from \
module '%s'\n", 1398},
  {"SelectModules: using\n", 1399},
  {"SelectModules: terminating search, only one %s module may be active\n", 1400},
  {"SelectModule: terminating search, all sound callbacks defined\n", 1401},
  {"SelectModules:  did not find a single usable %s module?\n", 1402},
  {"\
ValidateModules: must not be selected since only one %s module may be active \
at once\n", 1403},
  {"\
ValidateModules: must not be selected since other non-exclusive modules are \
already selected\n", 1404},
  {"\
ValidateModules: must not be selected since module '%s' defines the same \
callbacks\n", 1405},
  {"ValidateModules: no %s modules are selected; at least one is required\n", 1406},
  {"Tag: '%s', name: '%s', type: '%s'\n", 1407},
  {"\tFlags: ", 1408},
  {"exclusive ", 1409},
  {"[enable-once] ", 1410},
  {"enable-once ", 1411},
  {"[disable-once] ", 1412},
  {"disable-once ", 1413},
  {"in-use ", 1414},
  {"unselected ", 1415},
  {"\
No such v9t9 module '%s'\n\
\n", 1416},
  {"Module '%s' is unavailable, cannot toggle\n", 1417},
  {"V9t9 Module Commands", 1418},
  {"These options affect the modules used to emulate V9t9", 1419},
  {"List available modules and current status", 1420},
  {"Turn use of a module on or off", 1421},
  {"tag name for module", 1422},
  {"whether to use or not use module", 1423},
  {"Setup module gestalt", 1424},
  {"_New Session", 1425},
  {"_Load Configuration", 1426},
  {"Sa_ve Configuration", 1427},
  {"Save _Configuration As...", 1428},
  {"New File", 1429},
  {"Open File", 1430},
  {"Save File", 1431},
  {"dsr_set_active:  trying to install bogus module", 1432},
  {"Cannot connect to X server '%s'\n", 1433},
  {"Cannot create command thread\n", 1434},
  {"\
Event = %d\n\
\n\
\n", 1435},
  {"tick... %d\n", 1436},
  {"executing event with id=%d\n", 1437},
  {"\
freeing event with id=%d\n\
\n", 1438},
  {"\
\n\
Timer event list full\n", 1439},
  {"TM_SetEvent:\n", 1440},
};

int _msg_tbl_length = 1440;
