/**
 * 
 */
package ejs.base.sound;

import java.util.List;

/**
 * A listener for sound generated by {@link ISoundOutput}
 * before passed to {@link ISoundEmitter}.
 * @author ejs
 *
 */
public interface ISoundMutator {
	/**
	 * Edit a generated a sound chunk. 
	 * @param chunk
	 * @param outChunks edited chunks; over time, the output data 
	 * should match the time of the input data 
	 */
	void editSoundChunk(ISoundView chunk, List<SoundChunk> outChunks);
}