/*
  ISoundMutator.java

  (c) 2012 Edward Swartz

  All rights reserved. This program and the accompanying materials
  are made available under the terms of the Eclipse Public License v1.0
  which accompanies this distribution, and is available at
  http://www.eclipse.org/legal/epl-v10.html
 */
package ejs.base.sound;

import java.util.List;

/**
 * A listener for sound generated by {@link ISoundOutput}
 * before passed to {@link ISoundEmitter}.
 * @author ejs
 *
 */
public interface ISoundMutator {
	/**
	 * Edit a generated a sound chunk. 
	 * @param view
	 * @param outViews edited chunks; over time, the output data 
	 * should match the time of the input data 
	 */
	void editSoundChunk(ISoundView view, List<ISoundView> outViews);
}